'use client'

import { useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Package, Tag, Upload, Loader2, Boxes, Layers } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Select } from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import { cn } from '@/lib/utils'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogClose,
} from '@/components/ui/dialog'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  createProductRecord,
  updateProductRecord,
  generateProductCode,
  ProductFormData,
} from '@/lib/actions/products'
import { COMMON_UNITS, COMMON_CATEGORIES } from '@/lib/products'
import { VariantEditor } from '@/components/products/VariantEditor'

interface ProductFormProps {
  initialData?: Partial<ProductFormData> & { id?: string }
  onSuccess?: () => void
  redirectOnSuccess?: boolean
  isInCampaign?: boolean
}

function useProductForm(
  initialData?: Partial<ProductFormData> & { id?: string },
  isInCampaign?: boolean
) {
  const isEditing = Boolean(initialData?.id)
  const [formData, setFormData] = useState<ProductFormData>(() => ({
    code: initialData?.code ?? '',
    name: initialData?.name ?? '',
    description: initialData?.description ?? '',
    unit: initialData?.unit ?? 'EA',
    category: initialData?.category ?? '',
    default_price: initialData?.default_price ?? 0,
    image_url: initialData?.image_url ?? '',
    is_active: initialData?.is_active ?? true,
    price_from: initialData?.price_from ?? null,
    price_includes_vat: initialData?.price_includes_vat ?? false,
    length_mm: initialData?.length_mm ?? null,
    width_mm: initialData?.width_mm ?? null,
    height_mm: initialData?.height_mm ?? null,
    thickness_mm: initialData?.thickness_mm ?? null,
    coverage_m2_per_unit: initialData?.coverage_m2_per_unit ?? null,
    coverage_linear_m_per_unit: initialData?.coverage_linear_m_per_unit ?? null,
    unit_weight_kg: initialData?.unit_weight_kg ?? null,
    pack_size: initialData?.pack_size ?? null,
    wastage_pct: initialData?.wastage_pct != null ? Number(initialData.wastage_pct) : 5,
    calculator_type: initialData?.calculator_type ?? '',
    sale_price: initialData?.sale_price ?? null,
    sale_starts_at: initialData?.sale_starts_at ?? null,
    sale_ends_at: initialData?.sale_ends_at ?? null,
    sale_label: initialData?.sale_label ?? null,
    track_stock: initialData?.track_stock ?? false,
    stock_quantity: initialData?.stock_quantity ?? 0,
    reorder_level: initialData?.reorder_level ?? 0,
    auto_generate_code: initialData?.auto_generate_code ?? !isEditing,
    variant_options: initialData?.variant_options ?? null,
    materials: initialData?.materials ?? null,
    family_slug: initialData?.family_slug ?? '',
    search_tags: initialData?.search_tags ?? null,
  }))
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [autoGenerateCode, setAutoGenerateCode] = useState(!isEditing)
  const [visibilityDialog, setVisibilityDialog] = useState<'clear-sale' | 'campaign-block' | null>(null)
  const [pendingVisibilityMode, setPendingVisibilityMode] = useState<'from' | 'quote' | null>(null)
  // Tracks the last code we auto-generated from a category change so we can
  // safely overwrite it if the user changes category again before editing it.
  const [autoGeneratedCode, setAutoGeneratedCode] = useState<string | null>(null)
  // The user's explicitly chosen price-visibility mode. Tracked separately
  // from the underlying price values so we can freely switch modes without
  // losing data (e.g. going quote → show keeps the trade price intact).
  const [priceVisibilityMode, setPriceVisibilityMode] = useState<
    'show' | 'from' | 'quote'
  >(() => {
    const dp = initialData?.default_price ?? 0
    const pf = initialData?.price_from ?? 0
    if (pf > 0) return 'from'
    if (dp > 0) return 'show'
    return 'quote'
  })

  function handleChange<T extends keyof ProductFormData>(field: T, value: ProductFormData[T]) {
    setFormData((prev) => ({ ...prev, [field]: value }))
  }

  async function generateCodeFromCategory(value: string) {
    if (!value.trim()) return
    const result = await generateProductCode(value)
    if (result.error || !result.code) return
    handleChange('code', result.code)
    setAutoGeneratedCode(result.code)
  }

  async function handleCategoryChange(value: string) {
    handleChange('category', value)

    // Auto-generate when the toggle is on. For new products this is the default.
    // For existing products the user must explicitly enable auto-generation.
    if (!autoGenerateCode || !value.trim()) return

    await generateCodeFromCategory(value)
  }

  function handleToggleAutoGenerate(next: boolean) {
    setAutoGenerateCode(next)
    handleChange('auto_generate_code', next)

    if (next && formData.category && (!formData.code || formData.code === autoGeneratedCode)) {
      generateCodeFromCategory(formData.category)
    }
  }

  function applyVisibilityModeRaw(mode: 'from' | 'quote') {
    if (mode === 'from') {
      // Default price_from to the current trade price when empty.
      handleChange('price_from', formData.price_from ?? formData.default_price ?? null)
    }
    // 'quote' intentionally keeps form values intact. We only zero them out
    // at submit time (see submit()), so the user can switch back without
    // re-typing. This is what fixes "stuck on quote".
  }

  function confirmClearSaleAndApplyMode() {
    handleChange('sale_price', null)
    handleChange('sale_starts_at', null)
    handleChange('sale_ends_at', null)
    handleChange('sale_label', null)
    if (pendingVisibilityMode) {
      applyVisibilityModeRaw(pendingVisibilityMode)
      setPriceVisibilityMode(pendingVisibilityMode)
    }
    setVisibilityDialog(null)
    setPendingVisibilityMode(null)
  }

  function cancelVisibilityDialog() {
    setVisibilityDialog(null)
    setPendingVisibilityMode(null)
  }

  function applyVisibilityMode(mode: 'show' | 'from' | 'quote') {
    // Going TO 'show' is always allowed: just clears 'from' and reveals the
    // trade price field. Even when the product is currently in quote mode we
    // let users switch back without re-prompting (sale was already cleared
    // when they went into quote).
    if (mode === 'show') {
      handleChange('price_from', null)
      setPriceVisibilityMode('show')
      return
    }

    // Switching away from Show price to 'from' or 'quote' disables discounts.
    // If the product has an active/scheduled individual sale, ask before
    // clearing it. If it's in a campaign, block the change entirely — campaigns
    // must be edited separately.
    if (formData.sale_price != null) {
      setPendingVisibilityMode(mode)
      setVisibilityDialog('clear-sale')
      return
    }

    if (isInCampaign) {
      setVisibilityDialog('campaign-block')
      return
    }

    applyVisibilityModeRaw(mode)
    setPriceVisibilityMode(mode)
  }

  async function submit() {
    setLoading(true)
    setError(null)

    // In 'quote' mode the public page must see no prices, so zero them out at
    // the boundary. Form state keeps the user's typed values so a later
    // mode switch doesn't lose data.
    const payload: ProductFormData = {
      ...formData,
      auto_generate_code: autoGenerateCode,
      default_price:
        priceVisibilityMode === 'quote' ? 0 : formData.default_price ?? 0,
      price_from:
        priceVisibilityMode === 'quote' ? null : formData.price_from,
    }

    const result = isEditing
      ? await updateProductRecord(initialData!.id!, payload)
      : await createProductRecord(payload)

    setLoading(false)

    if (result.error) {
      setError(result.error)
      return false
    }

    return true
  }

  return {
    isEditing,
    formData,
    loading,
    error,
    autoGenerateCode,
    handleChange,
    handleCategoryChange,
    handleToggleAutoGenerate,
    applyVisibilityMode,
    submit,
    visibilityDialog,
    cancelVisibilityDialog,
    confirmClearSaleAndApplyMode,
    priceVisibilityMode,
  }
}

function FieldRow({
  label,
  htmlFor,
  required,
  align = 'start',
  children,
}: {
  label: React.ReactNode
  htmlFor?: string
  required?: boolean
  align?: 'center' | 'start'
  children: React.ReactNode
}) {
  return (
    <div
      className={`grid grid-cols-1 gap-2 sm:grid-cols-[160px_1fr] sm:items-${align} sm:gap-4`}
    >
      <Label
        htmlFor={htmlFor}
        className="pt-2 text-sm font-medium text-foreground sm:text-right"
      >
        {label}
        {required ? <span className="ml-0.5 text-destructive">*</span> : null}
      </Label>
      <div className="min-w-0">{children}</div>
    </div>
  )
}

/**
 * Pull every option `text` out of a variant_options JSONB in the
 * order they were declared. Used to compute the canonical
 * search_tags set the form auto-bakes when the operator edits
 * variants, so a typed size ("UB 127x76x13kg") matches the
 * consolidated product via the search RPC without us having to
 * teach the RPC about the variant_options JSON shape.
 */
function extractVariantLabels(
  variantOptions: unknown
): string[] {
  if (!Array.isArray(variantOptions)) return []
  const out: string[] = []
  for (const v of variantOptions) {
    if (!v || typeof v !== 'object') continue
    const options = (v as { options?: unknown }).options
    if (!Array.isArray(options)) continue
    for (const o of options) {
      if (!o || typeof o !== 'object') continue
      const text = (o as { text?: unknown }).text
      if (typeof text === 'string' && text.trim()) out.push(text)
    }
  }
  return out
}

/**
 * Merge the variant option labels into the existing search_tags array
 * without dropping manually-entered tags. De-duplicates on output so
 * the search index stays compact. Returns null when both inputs are
 * empty so we don't write `[]` to the DB unnecessarily.
 */
function mergeSearchTags(
  existing: string[] | null | undefined,
  sizeLabels: string[]
): string[] | null {
  const set = new Set<string>()
  for (const tag of existing ?? []) {
    if (typeof tag === 'string' && tag.trim()) set.add(tag.trim())
  }
  for (const label of sizeLabels) {
    if (label && label.trim()) set.add(label.trim())
  }
  return set.size > 0 ? Array.from(set) : null
}

function getSpecFieldVisibility(calculatorType: string) {
  switch (calculatorType) {
    case 'BRICK_WALL':
      return { dimensions: true, coverage: false, linearCoverage: false, unitWeight: false, packSize: true }
    case 'MORTAR_CONCRETE':
      return { dimensions: false, coverage: false, linearCoverage: false, unitWeight: true, packSize: true }
    case 'SHEET_MATERIALS':
      return { dimensions: true, coverage: false, linearCoverage: false, unitWeight: false, packSize: true }
    case 'AGGREGATES':
      return { dimensions: false, coverage: false, linearCoverage: false, unitWeight: false, packSize: true }
    case 'SCREED':
      return { dimensions: false, coverage: false, linearCoverage: false, unitWeight: true, packSize: true }
    case 'PLASTERING':
      return { dimensions: true, coverage: true, linearCoverage: false, unitWeight: false, packSize: true }
    case 'INSULATION':
      return { dimensions: true, coverage: true, linearCoverage: false, unitWeight: false, packSize: true }
    case 'ROOFING':
      return { dimensions: true, coverage: true, linearCoverage: true, unitWeight: false, packSize: true }
    case 'TIMBER':
      return { dimensions: true, coverage: false, linearCoverage: false, unitWeight: false, packSize: true }
    case 'STEEL_LINTEL':
      return { dimensions: true, coverage: false, linearCoverage: true, unitWeight: false, packSize: true }
    default:
      return { dimensions: false, coverage: false, linearCoverage: false, unitWeight: false, packSize: false }
  }
}

interface ProductSpecFieldsProps {
  calculatorType: string
  formData: ProductFormData
  onChange: <T extends keyof ProductFormData>(field: T, value: ProductFormData[T]) => void
}

function ProductSpecFields({ calculatorType, formData, onChange }: ProductSpecFieldsProps) {
  const visible = getSpecFieldVisibility(calculatorType)

  return (
    <div className="space-y-3">
      {visible.dimensions && (
        <FieldRow label="Dimensions (mm)" htmlFor="length_mm" align="start">
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
            <div className="space-y-1">
              <Label htmlFor="length_mm" className="text-xs text-muted-foreground">Length</Label>
              <Input
                id="length_mm"
                type="number"
                min={0}
                step={0.1}
                value={formData.length_mm ?? ''}
                onChange={(e) => onChange('length_mm', e.target.value ? parseFloat(e.target.value) : null)}
              />
            </div>
            <div className="space-y-1">
              <Label htmlFor="width_mm" className="text-xs text-muted-foreground">Width</Label>
              <Input
                id="width_mm"
                type="number"
                min={0}
                step={0.1}
                value={formData.width_mm ?? ''}
                onChange={(e) => onChange('width_mm', e.target.value ? parseFloat(e.target.value) : null)}
              />
            </div>
            <div className="space-y-1">
              <Label htmlFor="height_mm" className="text-xs text-muted-foreground">Height</Label>
              <Input
                id="height_mm"
                type="number"
                min={0}
                step={0.1}
                value={formData.height_mm ?? ''}
                onChange={(e) => onChange('height_mm', e.target.value ? parseFloat(e.target.value) : null)}
              />
            </div>
            <div className="space-y-1">
              <Label htmlFor="thickness_mm" className="text-xs text-muted-foreground">Thickness</Label>
              <Input
                id="thickness_mm"
                type="number"
                min={0}
                step={0.1}
                value={formData.thickness_mm ?? ''}
                onChange={(e) => onChange('thickness_mm', e.target.value ? parseFloat(e.target.value) : null)}
              />
            </div>
          </div>
        </FieldRow>
      )}

      {(visible.coverage || visible.linearCoverage || visible.unitWeight) && (
        <FieldRow label="Coverage / weight" htmlFor="coverage_m2_per_unit" align="start">
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-3">
            {visible.coverage && (
              <div className="space-y-1">
                <Label htmlFor="coverage_m2_per_unit" className="text-xs text-muted-foreground">m² / unit</Label>
                <Input
                  id="coverage_m2_per_unit"
                  type="number"
                  min={0}
                  step={0.01}
                  value={formData.coverage_m2_per_unit ?? ''}
                  onChange={(e) => onChange('coverage_m2_per_unit', e.target.value ? parseFloat(e.target.value) : null)}
                />
              </div>
            )}
            {visible.linearCoverage && (
              <div className="space-y-1">
                <Label htmlFor="coverage_linear_m_per_unit" className="text-xs text-muted-foreground">Linear m / unit</Label>
                <Input
                  id="coverage_linear_m_per_unit"
                  type="number"
                  min={0}
                  step={0.01}
                  value={formData.coverage_linear_m_per_unit ?? ''}
                  onChange={(e) => onChange('coverage_linear_m_per_unit', e.target.value ? parseFloat(e.target.value) : null)}
                />
              </div>
            )}
            {visible.unitWeight && (
              <div className="space-y-1">
                <Label htmlFor="unit_weight_kg" className="text-xs text-muted-foreground">Unit weight (kg)</Label>
                <Input
                  id="unit_weight_kg"
                  type="number"
                  min={0}
                  step={0.01}
                  value={formData.unit_weight_kg ?? ''}
                  onChange={(e) => onChange('unit_weight_kg', e.target.value ? parseFloat(e.target.value) : null)}
                />
              </div>
            )}
          </div>
        </FieldRow>
      )}

      {visible.packSize && (
        <FieldRow label="Pack size" htmlFor="pack_size">
          <Input
            id="pack_size"
            type="number"
            min={0}
            step={1}
            value={formData.pack_size ?? ''}
            onChange={(e) => onChange('pack_size', e.target.value ? parseInt(e.target.value, 10) : null)}
          />
        </FieldRow>
      )}
    </div>
  )
}

function useProductImages() {
  const [images, setImages] = useState<string[]>([])
  const [loading, setLoading] = useState(false)
  const [uploading, setUploading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false

    async function load() {
      setLoading(true)
      setError(null)
      try {
        const res = await fetch('/api/products/images')
        const data = await res.json()
        if (cancelled) return
        if (!res.ok) {
          throw new Error(data.error || 'Could not load images')
        }
        setImages(data.images ?? [])
      } catch (err) {
        if (cancelled) return
        setError(err instanceof Error ? err.message : 'Could not load images')
      } finally {
        if (!cancelled) setLoading(false)
      }
    }

    load()
    return () => {
      cancelled = true
    }
  }, [])

  async function uploadImage(file: File): Promise<string | null> {
    setUploading(true)
    setError(null)
    try {
      const formData = new FormData()
      formData.append('image', file)
      const res = await fetch('/api/products/images', {
        method: 'POST',
        body: formData,
      })
      const data = await res.json()
      if (!res.ok) {
        throw new Error(data.error || 'Could not upload image')
      }
      const uploaded = data.image as string
      // Refresh the dropdown list and keep the new image selected via onChange.
      const listRes = await fetch('/api/products/images')
      const listData = await listRes.json()
      if (listRes.ok) {
        setImages(listData.images ?? [])
      }
      return uploaded
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not upload image')
      return null
    } finally {
      setUploading(false)
    }
  }

  return { images, loading, uploading, error, uploadImage }
}

function ImageSelector({
  value,
  onChange,
}: {
  value: string
  onChange: (value: string) => void
}) {
  const { images, loading, uploading, error, uploadImage } = useProductImages()
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [selectedFile, setSelectedFile] = useState<File | null>(null)

  const options = [
    { value: '', label: 'No image' },
    ...images.map((img) => ({ value: img, label: img.replace('/products/', '') })),
  ]

  async function handleFileSelect(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    setSelectedFile(file)
    const uploaded = await uploadImage(file)
    if (uploaded) {
      onChange(uploaded)
    }
    setSelectedFile(null)
    if (fileInputRef.current) {
      fileInputRef.current.value = ''
    }
  }

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2">
        <div className="flex-1">
          <Select
            id="image_url"
            value={value}
            onChange={onChange}
            options={options}
            placeholder={loading ? 'Loading images...' : 'Select an image'}
            disabled={loading || uploading}
          />
        </div>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/webp,image/jpeg,image/png,image/gif,image/svg+xml"
          className="hidden"
          onChange={handleFileSelect}
        />
        <Button
          type="button"
          variant="outline"
          onClick={() => fileInputRef.current?.click()}
          disabled={uploading}
          className="shrink-0"
        >
          {uploading ? (
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          ) : (
            <Upload className="mr-2 h-4 w-4" />
          )}
          {uploading ? 'Uploading...' : 'Upload'}
        </Button>
      </div>

      {error && <p className="text-xs text-destructive">{error}</p>}

      {selectedFile && uploading && (
        <p className="text-xs text-muted-foreground">Uploading {selectedFile.name}...</p>
      )}

      {value && (
        <div className="relative mt-2 inline-block overflow-hidden rounded-lg border border-border bg-muted/30">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={value}
            alt="Selected product"
            className="h-32 w-32 object-contain"
          />
        </div>
      )}
    </div>
  )
}

export function ProductForm({
  initialData,
  onSuccess,
  redirectOnSuccess = false,
  isInCampaign,
}: ProductFormProps) {
  const router = useRouter()
  const {
    isEditing,
    formData,
    loading,
    error,
    autoGenerateCode,
    handleChange,
    handleCategoryChange,
    handleToggleAutoGenerate,
    applyVisibilityMode,
    submit,
    visibilityDialog,
    cancelVisibilityDialog,
    confirmClearSaleAndApplyMode,
    priceVisibilityMode,
  } = useProductForm(initialData, isInCampaign)

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const ok = await submit()
    if (!ok) return

    onSuccess?.()
    if (redirectOnSuccess) {
      router.push('/admin/products')
    }
  }

  const unitOptions = COMMON_UNITS.map((unit) => ({ value: unit, label: unit }))
  const categoryOptions = COMMON_CATEGORIES.map((category) => ({ value: category, label: category }))
  const calculatorTypeOptions = [
    { value: '', label: 'No calculator' },
    { value: 'BRICK_WALL', label: 'Brick & block wall' },
    { value: 'MORTAR_CONCRETE', label: 'Mortar & concrete mix' },
    { value: 'SHEET_MATERIALS', label: 'Sheet materials' },
    { value: 'AGGREGATES', label: 'Aggregates & sub-base' },
    { value: 'SCREED', label: 'Screed' },
    { value: 'PLASTERING', label: 'Plastering & board' },
    { value: 'INSULATION', label: 'Insulation' },
    { value: 'ROOFING', label: 'Roofing' },
    { value: 'TIMBER', label: 'Timber & studwork' },
    { value: 'STEEL_LINTEL', label: 'Steel & lintel selector' },
  ]

  // Source of truth for which Display-mode radio is selected. Tracks the
  // user's explicit choice so they can switch between modes freely without
  // getting stuck on 'quote' when both price fields happen to be zero.
  const displayMode: 'show' | 'from' | 'quote' = priceVisibilityMode

  return (
    <form onSubmit={handleSubmit} className="space-y-4 text-left">
      {error && (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      <Tabs defaultValue="general">
        {/*
          TabsList is now flex-wrap so the 4 tabs (Details / Variants /
          Pricing / Stock) always show even in the narrow inline-edit
          dialog. Without flex-wrap, the Variants tab would clip off the
          right edge on widths below ~640px and the operator would
          silently lose access to the variant editor and search tags.
        */}
        <TabsList className="flex h-auto flex-wrap gap-1 p-1 bg-muted/60 border border-border w-full">
          <TabsTrigger value="general" className="gap-2 px-4">
            <Package className="h-3.5 w-3.5" />
            Details
          </TabsTrigger>
          <TabsTrigger value="variants" className="gap-2 px-4">
            <Layers className="h-3.5 w-3.5" />
            Variants
          </TabsTrigger>
          <TabsTrigger value="pricing" className="gap-2 px-4">
            <Tag className="h-3.5 w-3.5" />
            Pricing
          </TabsTrigger>
          <TabsTrigger value="stock" className="gap-2 px-4">
            <Boxes className="h-3.5 w-3.5" />
            Stock
          </TabsTrigger>
        </TabsList>

        <TabsContent value="general" className="mt-4 space-y-4 focus-visible:outline-none">
          <FieldRow label="Name" htmlFor="name" required>
            <Input
              id="name"
              value={formData.name}
              onChange={(e) => handleChange('name', e.target.value)}
              placeholder="Product name"
              required
            />
          </FieldRow>

          <FieldRow label="Description" htmlFor="description" align="start">
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => handleChange('description', e.target.value)}
              placeholder="Short description shown on the public catalogue"
              rows={3}
            />
          </FieldRow>

          <FieldRow label="Unit" htmlFor="unit" required>
            <Select
              id="unit"
              value={formData.unit}
              onChange={(value) => handleChange('unit', value)}
              options={unitOptions}
            />
          </FieldRow>

          <FieldRow label="Category" htmlFor="category" required>
            <Select
              id="category"
              value={formData.category}
              onChange={(value) => handleCategoryChange(value)}
              options={categoryOptions}
              placeholder="Select a category"
              required
            />
          </FieldRow>

          <FieldRow label="Code" htmlFor="code" required>
            <div className="space-y-2">
              <div className="flex items-center gap-3">
                <Input
                  id="code"
                  value={formData.code}
                  onChange={(e) => handleChange('code', e.target.value.toUpperCase())}
                  placeholder="e.g. STL-007"
                  required
                  disabled={autoGenerateCode}
                  className={autoGenerateCode ? 'bg-muted/50' : undefined}
                />
              </div>
              <div className="flex items-center gap-2">
                <Switch
                  id="auto_generate_code"
                  checked={autoGenerateCode}
                  onCheckedChange={handleToggleAutoGenerate}
                  aria-label="Auto-generate product code"
                />
                <Label
                  htmlFor="auto_generate_code"
                  className="text-xs font-normal text-muted-foreground cursor-pointer"
                >
                  Auto-generate code from category
                </Label>
              </div>
            </div>
          </FieldRow>

          <FieldRow label="Image" htmlFor="image_url" align="start">
            <ImageSelector value={formData.image_url} onChange={(value) => handleChange('image_url', value)} />
          </FieldRow>

          {/* Calculator & product specifications */}
          <div className="rounded-lg border border-border bg-muted/30 p-4">
            <div className="mb-4">
              <h3 className="text-sm font-semibold text-foreground">Quantity calculator</h3>
              <p className="text-xs text-muted-foreground">
                Enable a calculator on the public product page and enter the specs it needs.
              </p>
            </div>

            <div className="space-y-4">
              <FieldRow label="Enable calculator" htmlFor="enable_calculator">
                <div className="flex items-center gap-2">
                  <Switch
                    id="enable_calculator"
                    checked={formData.calculator_type !== ''}
                    onCheckedChange={(checked) =>
                      handleChange(
                        'calculator_type',
                        // Toggling on with no type yet must pick a real type —
                        // the type selector only renders once the value is
                        // non-empty, so defaulting to '' dead-ended the
                        // feature (switch could never be enabled).
                        checked ? formData.calculator_type || 'BRICK_WALL' : ''
                      )
                    }
                    aria-label="Enable quantity calculator"
                  />
                  <Label
                    htmlFor="enable_calculator"
                    className="text-xs font-normal text-muted-foreground cursor-pointer"
                  >
                    Show a &ldquo;calculate how much you need&rdquo; tool on the public page
                  </Label>
                </div>
              </FieldRow>

              {formData.calculator_type !== '' && (
                <>
                  <FieldRow label="Calculator type" htmlFor="calculator_type">
                    <Select
                      id="calculator_type"
                      value={formData.calculator_type}
                      onChange={(value) => handleChange('calculator_type', value)}
                      options={calculatorTypeOptions}
                      placeholder="Select a calculator"
                    />
                  </FieldRow>

                  <ProductSpecFields
                    calculatorType={formData.calculator_type}
                    formData={formData}
                    onChange={handleChange}
                  />
                </>
              )}
            </div>
          </div>
        </TabsContent>

        <TabsContent value="variants" className="mt-4 space-y-4 focus-visible:outline-none">
          <div className="rounded-lg border border-border bg-white p-5">
            <div className="mb-4">
              <h3 className="text-sm font-semibold text-foreground">Variants</h3>
              <p className="text-xs text-muted-foreground">
                Add a variant when this product comes in multiple sizes or
                specs. Each option becomes a dropdown on the public
                product page. Attach measurements (length, weight,
                diameter, etc.) to any option that needs per-size
                metadata — leave the section empty when the product
                doesn&rsquo;t need it.
              </p>
            </div>

            <VariantEditor
              value={Array.isArray(formData.variant_options) ? formData.variant_options : null}
              onChange={(next) => {
                handleChange('variant_options', next)
                // Re-bake search_tags so dropping an option from the
                // editor also drops it from the search index. Existing
                // manual tags are preserved — the operator can still
                // manage them in the "Search tags" field further down.
                handleChange(
                  'search_tags',
                  mergeSearchTags(
                    formData.search_tags,
                    extractVariantLabels(next)
                  )
                )
              }}
            />

            <div className="my-5 border-t border-border" />

            <div className="grid gap-3 sm:grid-cols-2">
              <FieldRow label="Materials" htmlFor="materials" align="start">
                <Input
                  id="materials"
                  value={(formData.materials ?? []).join(', ')}
                  onChange={(e) =>
                    handleChange(
                      'materials',
                      e.target.value
                        .split(',')
                        .map((m) => m.trim())
                        .filter(Boolean)
                    )
                  }
                  placeholder="Mild steel, Bright steel, Stainless steel"
                />
                <p className="text-xs text-muted-foreground">
                  Comma-separated. Used for the schema.org/Product.material field.
                </p>
              </FieldRow>
              <FieldRow label="Family slug" htmlFor="family_slug">
                <Input
                  id="family_slug"
                  value={formData.family_slug ?? ''}
                  onChange={(e) => handleChange('family_slug', e.target.value)}
                  placeholder="e.g. universal-beam"
                />
                <p className="text-xs text-muted-foreground">
                  URL slug for the product family. Optional.
                </p>
              </FieldRow>
              <FieldRow label="Search tags" htmlFor="search_tags" align="start">
                <Textarea
                  id="search_tags"
                  value={(formData.search_tags ?? []).join(', ')}
                  onChange={(e) =>
                    handleChange(
                      'search_tags',
                      Array.from(
                        new Set(
                          e.target.value
                            .split(/[\n,]+/)
                            .map((t) => t.trim())
                            .filter(Boolean)
                        )
                      )
                    )
                  }
                  rows={3}
                  placeholder="universal beam, rsj, structural steel, ub 127x76x13kg, ..."
                />
                <p className="text-xs text-muted-foreground">
                  Comma- or newline-separated. Indexed at weight C by
                  the search RPC. Auto-populated from the variant
                  options above — add or remove tags here for synonyms
                  that aren&rsquo;t options.
                </p>
              </FieldRow>
            </div>
          </div>
        </TabsContent>

        <TabsContent value="pricing" className="mt-4 space-y-4 focus-visible:outline-none">
          {/* CARD 1: PRICE VISIBILITY */}
          <div className="rounded-lg border border-border bg-white p-5">
            <div className="mb-4">
              <h3 className="text-sm font-semibold text-foreground">Price visibility</h3>
              <p className="text-xs text-muted-foreground">
                Choose what visitors see on the public product page. You can publish a single
                price, a &ldquo;from&rdquo; starting price, or hide the price entirely and ask
                for a quote.
              </p>
            </div>

            <div className="space-y-4">
              <FieldRow label="Display mode" htmlFor="price_visibility_mode">
                <div className="grid gap-2 sm:grid-cols-3">
                  {(
                    [
                      { value: 'show', label: 'Show price', help: 'Publishes a clean per-unit price.' },
                      { value: 'from', label: 'Show "from"', help: 'Lowest entry-point across sizes.' },
                      { value: 'quote', label: 'Hide · quote only', help: 'Shows "Trade price on application".' },
                    ] as const
                  ).map((opt) => {
                    const active = opt.value === displayMode
                    return (
                      <label
                        key={opt.value}
                        className={`flex cursor-pointer items-start gap-3 rounded-lg border p-3 transition-colors ${
                          active
                            ? 'border-primary bg-primary/5'
                            : 'border-border bg-white hover:border-primary/40'
                        }`}
                      >
                        <input
                          type="radio"
                          name="price_visibility_mode"
                          checked={active}
                          onChange={() => applyVisibilityMode(opt.value)}
                          className="mt-1"
                        />
                        <div>
                          <div className="text-sm font-semibold text-foreground">{opt.label}</div>
                          <div className="text-xs text-muted-foreground">{opt.help}</div>
                        </div>
                      </label>
                    )
                  })}
                </div>
              </FieldRow>

              {displayMode === 'quote' ? (
                /* Quote-only: nothing to fill in — visitors see "Trade price on
                 * application" on the public page, so we don't capture any
                 * prices in the form. (Stored values are zeroed on submit.) */
                <div className="rounded-md border border-dashed border-border bg-muted/30 px-4 py-3">
                  <p className="text-xs text-muted-foreground">
                    This product is hidden behind a quote. Visitors see{' '}
                    <span className="font-medium text-foreground">
                      &ldquo;Trade price on application&rdquo;
                    </span>{' '}
                    on the public page — no prices are stored.
                  </p>
                </div>
              ) : displayMode === 'show' ? (
                /* Show price: just the trade price + VAT toggle. */
                <>
                  <FieldRow label="Trade price (£)" htmlFor="default_price" required>
                    <div>
                      <div className="flex">
                        <span className="inline-flex items-center rounded-l-md border border-r-0 border-border bg-muted/40 px-3 text-sm text-muted-foreground">£</span>
                        <Input
                          id="default_price"
                          type="number"
                          min={0}
                          step={0.01}
                          value={formData.default_price || ''}
                          onChange={(e) => handleChange('default_price', parseFloat(e.target.value) || 0)}
                          placeholder="0.00"
                          className="rounded-l-none"
                        />
                      </div>
                      <p className="mt-1 text-xs text-muted-foreground">
                        Your internal trade price. Used on invoices, reports and the public page.
                      </p>
                      <p className="mt-1 text-xs text-muted-foreground">
                        Want a <span className="font-medium text-foreground">&ldquo;From £X&rdquo;</span> starting
                        price instead? Switch Display mode to{' '}
                        <span className="font-medium text-foreground">Show &ldquo;from&rdquo;</span>.
                      </p>
                    </div>
                  </FieldRow>

                  {/* VAT toggle: only relevant when there's actually a price
                   * displayed, so it disappears in 'quote' mode. */}
                  <FieldRow label="VAT" htmlFor="price_includes_vat">
                    <label className="flex items-center gap-2 text-sm">
                      <input
                        id="price_includes_vat"
                        type="checkbox"
                        checked={formData.price_includes_vat}
                        onChange={(e) => handleChange('price_includes_vat', e.target.checked)}
                        className="h-4 w-4 rounded border-border"
                      />
                      <span>Prices include VAT @ 20%</span>
                    </label>
                    <p className="mt-1 text-xs text-muted-foreground">
                      Default: VAT exclusive (standard for trade pricing).
                    </p>
                  </FieldRow>
                </>
              ) : (
                /* From mode: only the "From" price + VAT toggle. Trade price is
                 * hidden here because showing both would defeat the purpose of
                 * a "From £X" teaser. */
                <>
                  <FieldRow
                    label={<>“From” price</>}
                    htmlFor="price_from"
                    required
                  >
                    <div>
                      <div className="flex">
                        <span className="inline-flex items-center rounded-l-md border border-r-0 border-border bg-muted/40 px-3 text-sm text-muted-foreground">£</span>
                        <Input
                          id="price_from"
                          type="number"
                          min={0}
                          step={0.01}
                          value={formData.price_from ?? ''}
                          onChange={(e) =>
                            handleChange(
                              'price_from',
                              e.target.value === '' ? null : parseFloat(e.target.value)
                            )
                          }
                          placeholder="0.00"
                          className="rounded-l-none"
                        />
                      </div>
                      <div className="mt-1 flex items-center justify-between gap-2">
                          <p className="text-xs text-muted-foreground">
                            Shown as &ldquo;From £0.00 per unit&rdquo; on the public page.
                          </p>
                          <button
                            type="button"
                            onClick={() => handleChange('price_from', formData.default_price || null)}
                            className="text-xs font-medium text-primary hover:underline"
                          >
                            Auto-fill from trade price
                          </button>
                        </div>
                        {formData.price_from != null &&
                          formData.price_from > formData.default_price &&
                          formData.default_price > 0 && (
                            <p className="mt-1 text-xs text-destructive">
                              &ldquo;From&rdquo; price cannot exceed the trade price.
                            </p>
                          )}
                       </div>
                    </FieldRow>

                  {/* VAT toggle: only relevant when there's actually a price
                   * displayed, so it disappears in 'quote' mode. */}
                  <FieldRow label="VAT" htmlFor="price_includes_vat">
                    <label className="flex items-center gap-2 text-sm">
                      <input
                        id="price_includes_vat"
                        type="checkbox"
                        checked={formData.price_includes_vat}
                        onChange={(e) => handleChange('price_includes_vat', e.target.checked)}
                        className="h-4 w-4 rounded border-border"
                      />
                      <span>Prices include VAT @ 20%</span>
                    </label>
                    <p className="mt-1 text-xs text-muted-foreground">
                      Default: VAT exclusive (standard for trade pricing).
                    </p>
                  </FieldRow>
                </>
              )}
            </div>
          </div>

          {/* Footnote: future Trade & volume tiers */}
          <p className="pt-1 text-[11px] text-muted-foreground">
            <span className="mr-1.5 inline-flex items-center rounded bg-muted px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
              Coming soon
            </span>
            Trade &amp; volume tiers (per-account percentage discounts and bulk-buy
            price breaks) will appear here once the customer-account tier feature ships.
          </p>
        </TabsContent>

        <TabsContent value="stock" className="mt-4 space-y-4 focus-visible:outline-none">
          <div className="rounded-lg border border-border bg-white p-5">
            <div className="mb-4">
              <h3 className="text-sm font-semibold text-foreground">Stock tracking</h3>
              <p className="text-xs text-muted-foreground">
                Track warehouse stock for this product. Stock is only deducted when
                company-wide stock routing is enabled.
              </p>
            </div>

            <div className="space-y-4">
              <FieldRow label="Track stock" htmlFor="track_stock">
                <div className="flex items-center gap-2">
                  <Switch
                    id="track_stock"
                    checked={formData.track_stock}
                    onCheckedChange={(checked) => handleChange('track_stock', checked)}
                    aria-label="Track stock for this product"
                  />
                  <Label
                    htmlFor="track_stock"
                    className="text-xs font-normal text-muted-foreground cursor-pointer"
                  >
                    Deduct stock when invoices containing this product are sent
                  </Label>
                </div>
              </FieldRow>

              {formData.track_stock && (
                <>
                  <FieldRow label="Stock quantity" htmlFor="stock_quantity">
                    <Input
                      id="stock_quantity"
                      type="number"
                      min={0}
                      step={0.001}
                      value={formData.stock_quantity}
                      onChange={(e) => handleChange('stock_quantity', parseFloat(e.target.value) || 0)}
                      readOnly={isEditing}
                      disabled={isEditing}
                    />
                    {isEditing ? (
                      <p className="text-xs text-muted-foreground mt-1">
                        Stock levels can only be changed from the Stock tab — this keeps
                        invoice deductions and stock takes from being overwritten when the
                        product is edited.
                      </p>
                    ) : null}
                  </FieldRow>

                  <FieldRow label="Reorder level" htmlFor="reorder_level">
                    <Input
                      id="reorder_level"
                      type="number"
                      min={0}
                      step={0.001}
                      value={formData.reorder_level}
                      onChange={(e) => handleChange('reorder_level', parseFloat(e.target.value) || 0)}
                    />
                    <p className="text-xs text-muted-foreground mt-1">
                      When stock falls to or below this level, a low-stock alert is raised.
                    </p>
                  </FieldRow>
                </>
              )}
            </div>
          </div>
        </TabsContent>

      </Tabs>

      <Dialog open={visibilityDialog === 'clear-sale'} onOpenChange={(open) => !open && cancelVisibilityDialog()}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Clear product discount?</DialogTitle>
            <DialogDescription>
              Switching away from Show price will remove this product&apos;s individual
              discount. You can manage discounts under Campaigns {'>'} Product discounts.
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-end gap-2 pt-2">
            <Button type="button" variant="outline" onClick={cancelVisibilityDialog}>
              Cancel
            </Button>
            <Button type="button" onClick={confirmClearSaleAndApplyMode}>
              Clear discount & switch
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      <Dialog open={visibilityDialog === 'campaign-block'} onOpenChange={(open) => !open && cancelVisibilityDialog()}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Product is in a campaign</DialogTitle>
            <DialogDescription>
              This product is part of a running campaign, so its price display mode
              cannot be changed here. Remove it from the campaign first under{' '}
              <strong>Campaigns {'>'} Campaign groups</strong>.
            </DialogDescription>
          </DialogHeader>
          <div className="flex justify-end gap-2 pt-2">
            <Button type="button" onClick={cancelVisibilityDialog}>
              Got it
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      <div className="flex flex-wrap items-center justify-end gap-3 pt-4 border-t border-border">
        <Button
          type="button"
          variant="outline"
          onClick={() => (redirectOnSuccess ? router.push('/admin/products') : undefined)}
          disabled={loading}
        >
          Cancel
        </Button>
        <Button type="submit" disabled={loading}>
          {loading ? 'Saving...' : isEditing ? 'Update Product' : 'Add Product'}
        </Button>
      </div>
    </form>
  )
}

interface ProductFormDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  initialData?: Partial<ProductFormData> & { id?: string }
  onSuccess?: () => void
}

export function ProductFormDialog({
  open,
  onOpenChange,
  initialData,
  onSuccess,
}: ProductFormDialogProps) {
  const isEditing = Boolean(initialData?.id)
  const [isInCampaign, setIsInCampaign] = useState(false)

  useEffect(() => {
    if (!open || !initialData?.id) {
      setIsInCampaign(false)
      return
    }

    const productId = initialData.id!
    let cancelled = false
    async function load() {
      const { getActiveCampaignForProduct } = await import('@/lib/actions/campaigns')
      const campaign = await getActiveCampaignForProduct(productId)
      if (!cancelled) setIsInCampaign(campaign != null)
    }
    load()
    return () => {
      cancelled = true
    }
  }, [open, initialData?.id])

  function handleSuccess() {
    onSuccess?.()
    onOpenChange(false)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogClose onClick={() => onOpenChange(false)} />
        <DialogHeader>
          <DialogTitle>{isEditing ? 'Edit Product' : 'Add Product'}</DialogTitle>
          <DialogDescription>
            {isEditing
              ? 'Update the product details below.'
              : 'Add a new product to the catalog.'}
          </DialogDescription>
        </DialogHeader>

        <ProductForm initialData={initialData} onSuccess={handleSuccess} isInCampaign={isInCampaign} />
      </DialogContent>
    </Dialog>
  )
}
