// lib/delivery-areas.ts
// Centralised delivery-area towns for the public site. The 50-mile own-fleet
// delivery round is anchored on the Iver yard and reaches across the South
// East, Greater London, parts of the South Midlands, north Essex, north Kent
// and the south coast. Towns are grouped by the main delivery hub each
// sub-town sits under so the /locations/[town] pages can pull a clean
// "areas near {hub}" cluster and we never link from a Slough page to a town
// that's 50 miles outside the actual delivery round.
//
// Geography is sourced from the official UK postcode maps (SL, HP, RG, GU,
// OX, SN, TW, UB, HA, WD, AL, LU, MK, SG, EN, CM, SS, DA, ME, TN, BR, CR,
// RH, BN, SO, PO, SP postcode areas) using post towns from the Royal Mail
// Address Management Guide as the authoritative source of which settlements
// sit inside each postcode area.
//
// The list is split into 13 hub sub-arrays and merged into DELIVERY_AREAS
// via spread. This keeps TypeScript's inferred literal type for each group
// small enough to typecheck — a single 1000+ entry array literal would
// produce a union that's too complex (TS2590).

export interface DeliveryArea {
  name: string
  slug: string
  county: string
  /**
   * The main delivery hub this sub-town sits under. Drives the "areas near
   * {hub} we also deliver to" group ordering on /locations/[town] pages
   * and the internal-link cluster.
   */
  hub: DeliveryHub
}

export type DeliveryHub =
  | 'slough' // core home — SL + outer west London (UB, TW, HA, WD)
  | 'high-wycombe' // Buckinghamshire + Bedfordshire + Hertfordshire north
  | 'reading' // west + central Berkshire
  | 'guildford' // Surrey + north Sussex
  | 'basingstoke' // north Hampshire + Salisbury Plain
  | 'oxford' // Oxfordshire
  | 'swindon' // Wiltshire
  | 'london' // Greater London boroughs + outer (EN, RM, IG, BR, DA)
  | 'luton' // Bedfordshire + Hertfordshire (Luton post town)
  | 'southend' // Essex (Chelmsford + Southend-on-Sea post towns)
  | 'maidstone' // Kent (Medway + Maidstone + Tonbridge post towns)
  | 'brighton' // East + West Sussex (Brighton + Crawley post towns)
  | 'portsmouth' // south Hampshire + Isle of Wight

// ─── Slough hub (SL postcode area) — east Berkshire + south Buckinghamshire
// + Royal Borough of Windsor & Maidenhead + outer West London (UB/TW/HA)
const SLOUGH_AREAS: DeliveryArea[] = [
  { name: 'Slough', slug: 'slough', county: 'Berkshire', hub: 'slough' },

  // SL0 — Iver post town
  { name: 'Iver', slug: 'iver', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Iver Heath', slug: 'iver-heath', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Richings Park', slug: 'richings-park', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Swansea Village', slug: 'swansea-village', county: 'Buckinghamshire', hub: 'slough' },

  // SL1 — Slough post town
  { name: 'Burnham', slug: 'burnham', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Burnham Beeches', slug: 'burnham-beeches', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Cippenham', slug: 'cippenham', county: 'Slough', hub: 'slough' },
  { name: 'Farnham Common', slug: 'farnham-common', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Farnham Royal', slug: 'farnham-royal', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Stoke Poges', slug: 'stoke-poges', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Littleworth', slug: 'littleworth', county: 'Buckinghamshire', hub: 'slough' },

  // SL2 — Slough post town
  { name: 'Britwell', slug: 'britwell', county: 'Slough', hub: 'slough' },
  { name: 'Hedgerley', slug: 'hedgerley', county: 'Buckinghamshire', hub: 'slough' },

  // SL3 — Slough post town
  { name: 'Langley', slug: 'langley', county: 'Berkshire', hub: 'slough' },
  { name: 'Datchet', slug: 'datchet', county: 'Berkshire', hub: 'slough' },
  { name: 'Colnbrook', slug: 'colnbrook', county: 'Berkshire', hub: 'slough' },
  { name: 'Poyle', slug: 'poyle', county: 'Berkshire', hub: 'slough' },
  { name: 'Horton', slug: 'horton', county: 'Berkshire', hub: 'slough' },
  { name: 'Fulmer', slug: 'fulmer', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'George Green', slug: 'george-green', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Wexham', slug: 'wexham', county: 'Buckinghamshire', hub: 'slough' },

  // SL4 — Windsor post town
  { name: 'Windsor', slug: 'windsor', county: 'Berkshire', hub: 'slough' },
  { name: 'Old Windsor', slug: 'old-windsor', county: 'Berkshire', hub: 'slough' },
  { name: 'Eton', slug: 'eton', county: 'Berkshire', hub: 'slough' },
  { name: 'Eton Wick', slug: 'eton-wick', county: 'Berkshire', hub: 'slough' },
  { name: 'Clewer', slug: 'clewer', county: 'Berkshire', hub: 'slough' },
  { name: 'Dedworth', slug: 'dedworth', county: 'Berkshire', hub: 'slough' },
  { name: 'Cranbourne', slug: 'cranbourne', county: 'Berkshire', hub: 'slough' },
  { name: 'Winkfield', slug: 'winkfield', county: 'Berkshire', hub: 'slough' },
  { name: 'Dorney', slug: 'dorney', county: 'Buckinghamshire', hub: 'slough' },

  // SL5 — Ascot post town
  { name: 'Ascot', slug: 'ascot', county: 'Berkshire', hub: 'slough' },
  { name: 'Sunninghill', slug: 'sunninghill', county: 'Berkshire', hub: 'slough' },
  { name: 'Sunningdale', slug: 'sunningdale', county: 'Berkshire', hub: 'slough' },
  { name: 'North Ascot', slug: 'north-ascot', county: 'Berkshire', hub: 'slough' },
  { name: 'South Ascot', slug: 'south-ascot', county: 'Berkshire', hub: 'slough' },

  // SL6 — Maidenhead post town
  { name: 'Maidenhead', slug: 'maidenhead', county: 'Berkshire', hub: 'slough' },
  { name: 'Taplow', slug: 'taplow', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Cookham', slug: 'cookham', county: 'Berkshire', hub: 'slough' },
  { name: 'Cookham Dean', slug: 'cookham-dean', county: 'Berkshire', hub: 'slough' },
  { name: 'Holyport', slug: 'holyport', county: 'Berkshire', hub: 'slough' },
  { name: 'Furze Platt', slug: 'furze-platt', county: 'Berkshire', hub: 'slough' },
  { name: 'Pinkneys Green', slug: 'pinkneys-green', county: 'Berkshire', hub: 'slough' },
  { name: 'Bray', slug: 'bray', county: 'Berkshire', hub: 'slough' },
  { name: 'Hurley', slug: 'hurley', county: 'Berkshire', hub: 'slough' },
  { name: 'White Waltham', slug: 'white-waltham', county: 'Berkshire', hub: 'slough' },

  // SL7 — Marlow post town
  { name: 'Marlow', slug: 'marlow', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Marlow Bottom', slug: 'marlow-bottom', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Little Marlow', slug: 'little-marlow', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Medmenham', slug: 'medmenham', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Bisham', slug: 'bisham', county: 'Berkshire', hub: 'slough' },

  // SL8 — Bourne End post town
  { name: 'Bourne End', slug: 'bourne-end', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Well End', slug: 'well-end', county: 'Buckinghamshire', hub: 'slough' },

  // SL9 — Gerrards Cross post town
  { name: 'Gerrards Cross', slug: 'gerrards-cross', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Chalfont St Peter', slug: 'chalfont-st-peter', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Chalfont Common', slug: 'chalfont-common', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Chalfont St Giles', slug: 'chalfont-st-giles', county: 'Buckinghamshire', hub: 'slough' },
  { name: 'Jordans', slug: 'jordans', county: 'Buckinghamshire', hub: 'slough' },

  // Outer West London (UB, TW, HA postcodes) — close to Iver
  { name: 'Uxbridge', slug: 'uxbridge', county: 'Greater London', hub: 'slough' },
  { name: 'Hillingdon', slug: 'hillingdon', county: 'Greater London', hub: 'slough' },
  { name: 'Hayes', slug: 'hayes', county: 'Greater London', hub: 'slough' },
  { name: 'West Drayton', slug: 'west-drayton', county: 'Greater London', hub: 'slough' },
  { name: 'Northwood', slug: 'northwood', county: 'Greater London', hub: 'slough' },
  { name: 'Ruislip', slug: 'ruislip', county: 'Greater London', hub: 'slough' },
  { name: 'Eastcote', slug: 'eastcote', county: 'Greater London', hub: 'slough' },
  { name: 'Pinner', slug: 'pinner', county: 'Greater London', hub: 'slough' },
  { name: 'Harefield', slug: 'harefield', county: 'Greater London', hub: 'slough' },
  { name: 'Ickenham', slug: 'ickenham', county: 'Greater London', hub: 'slough' },
  { name: 'Hillingdon Heath', slug: 'hillingdon-heath', county: 'Greater London', hub: 'slough' },
  { name: 'North Hillingdon', slug: 'north-hillingdon', county: 'Greater London', hub: 'slough' },
  { name: 'Yiewsley', slug: 'yiewsley', county: 'Greater London', hub: 'slough' },
]

// ─── High Wycombe hub (HP + parts of MK and north Buckinghamshire)
const HIGH_WYCOMBE_AREAS: DeliveryArea[] = [
  { name: 'High Wycombe', slug: 'high-wycombe', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Beaconsfield', slug: 'beaconsfield', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Seer Green', slug: 'seer-green', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Penn', slug: 'penn', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Flackwell Heath', slug: 'flackwell-heath', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Loudwater', slug: 'loudwater', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Wooburn', slug: 'wooburn', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Wooburn Green', slug: 'wooburn-green', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Tylers Green', slug: 'tylers-green', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Hazlemere', slug: 'hazlemere', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Holmer Green', slug: 'holmer-green', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Great Kingshill', slug: 'great-kingshill', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Downley', slug: 'downley', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'West Wycombe', slug: 'west-wycombe', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Stokenchurch', slug: 'stokenchurch', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Lane End', slug: 'lane-end', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Naphill', slug: 'naphill', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Great Missenden', slug: 'great-missenden', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Prestwood', slug: 'prestwood', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Little Chalfont', slug: 'little-chalfont', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Amersham', slug: 'amersham', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Chesham', slug: 'chesham', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Aylesbury', slug: 'aylesbury', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Wendover', slug: 'wendover', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Stoke Mandeville', slug: 'stoke-mandeville', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Princes Risborough', slug: 'princes-risborough', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Monks Risborough', slug: 'monks-risborough', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Winslow', slug: 'winslow', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Wing', slug: 'wing', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Haddenham', slug: 'haddenham', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Long Crendon', slug: 'long-crendon', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Bierton', slug: 'bierton', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Wingrave', slug: 'wingrave', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Cheddington', slug: 'cheddington', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Pitstone', slug: 'pitstone', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Ivinghoe', slug: 'ivinghoe', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Stewkley', slug: 'stewkley', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Swanbourne', slug: 'swanbourne', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Grendon Underwood', slug: 'grendon-underwood', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Westcott', slug: 'westcott', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Wotton Underwood', slug: 'wotton-underwood', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Kimble', slug: 'kimble', county: 'Buckinghamshire', hub: 'high-wycombe' },
  { name: 'Great Hampden', slug: 'great-hampden', county: 'Buckinghamshire', hub: 'high-wycombe' },
]

// ─── Reading hub (RG postcode area) — west + central Berkshire
const READING_AREAS: DeliveryArea[] = [
  { name: 'Reading', slug: 'reading', county: 'Berkshire', hub: 'reading' },
  { name: 'Caversham', slug: 'caversham', county: 'Berkshire', hub: 'reading' },
  { name: 'Tilehurst', slug: 'tilehurst', county: 'Berkshire', hub: 'reading' },
  { name: 'Woodley', slug: 'woodley', county: 'Berkshire', hub: 'reading' },
  { name: 'Earley', slug: 'earley', county: 'Berkshire', hub: 'reading' },
  { name: 'Calcot', slug: 'calcot', county: 'Berkshire', hub: 'reading' },
  { name: 'Theale', slug: 'theale', county: 'Berkshire', hub: 'reading' },
  { name: 'Pangbourne', slug: 'pangbourne', county: 'Berkshire', hub: 'reading' },
  { name: 'Sonning Common', slug: 'sonning-common', county: 'Oxfordshire', hub: 'reading' },
  { name: 'Goring-on-Thames', slug: 'goring-on-thames', county: 'Oxfordshire', hub: 'reading' },
  { name: 'Twyford', slug: 'twyford', county: 'Berkshire', hub: 'reading' },
  { name: 'Wargrave', slug: 'wargrave', county: 'Berkshire', hub: 'reading' },
  { name: 'Charvil', slug: 'charvil', county: 'Berkshire', hub: 'reading' },
  { name: 'Hurst', slug: 'hurst', county: 'Berkshire', hub: 'reading' },
  { name: 'Sonning', slug: 'sonning', county: 'Berkshire', hub: 'reading' },
  { name: 'Henley-on-Thames', slug: 'henley-on-thames', county: 'Oxfordshire', hub: 'reading' },
  { name: 'Shiplake', slug: 'shiplake', county: 'Oxfordshire', hub: 'reading' },
  { name: 'Bracknell', slug: 'bracknell', county: 'Berkshire', hub: 'reading' },
  { name: 'Crowthorne', slug: 'crowthorne', county: 'Berkshire', hub: 'reading' },
  { name: 'Sandhurst', slug: 'sandhurst', county: 'Berkshire', hub: 'reading' },
  { name: 'Wokingham', slug: 'wokingham', county: 'Berkshire', hub: 'reading' },
  { name: 'Winnersh', slug: 'winnersh', county: 'Berkshire', hub: 'reading' },
  { name: 'Finchampstead', slug: 'finchampstead', county: 'Berkshire', hub: 'reading' },
  { name: 'Binfield', slug: 'binfield', county: 'Berkshire', hub: 'reading' },
  { name: 'Warfield', slug: 'warfield', county: 'Berkshire', hub: 'reading' },
  { name: 'Newbury', slug: 'newbury', county: 'Berkshire', hub: 'reading' },
  { name: 'Thatcham', slug: 'thatcham', county: 'Berkshire', hub: 'reading' },
  { name: 'Hungerford', slug: 'hungerford', county: 'Berkshire', hub: 'reading' },
  { name: 'Lambourn', slug: 'lambourn', county: 'Berkshire', hub: 'reading' },
  { name: 'Kintbury', slug: 'kintbury', county: 'Berkshire', hub: 'reading' },
  { name: 'Burghfield', slug: 'burghfield', county: 'Berkshire', hub: 'reading' },
  { name: 'Mortimer', slug: 'mortimer', county: 'Berkshire', hub: 'reading' },
]

// ─── Guildford hub (GU postcode area) — Surrey + north Sussex
const GUILDFORD_AREAS: DeliveryArea[] = [
  { name: 'Guildford', slug: 'guildford', county: 'Surrey', hub: 'guildford' },
  { name: 'Woking', slug: 'woking', county: 'Surrey', hub: 'guildford' },
  { name: 'Godalming', slug: 'godalming', county: 'Surrey', hub: 'guildford' },
  { name: 'Cranleigh', slug: 'cranleigh', county: 'Surrey', hub: 'guildford' },
  { name: 'Haslemere', slug: 'haslemere', county: 'Surrey', hub: 'guildford' },
  { name: 'Farnham', slug: 'farnham', county: 'Surrey', hub: 'guildford' },
  { name: 'Camberley', slug: 'camberley', county: 'Surrey', hub: 'guildford' },
  { name: 'Frimley', slug: 'frimley', county: 'Surrey', hub: 'guildford' },
  { name: 'Bagshot', slug: 'bagshot', county: 'Surrey', hub: 'guildford' },
  { name: 'Lightwater', slug: 'lightwater', county: 'Surrey', hub: 'guildford' },
  { name: 'Yateley', slug: 'yateley', county: 'Hampshire', hub: 'guildford' },
  { name: 'Blackwater', slug: 'blackwater', county: 'Hampshire', hub: 'guildford' },
  { name: 'Fleet', slug: 'fleet', county: 'Hampshire', hub: 'guildford' },
  { name: 'Farnborough', slug: 'farnborough', county: 'Hampshire', hub: 'guildford' },
  { name: 'Aldershot', slug: 'aldershot', county: 'Hampshire', hub: 'guildford' },
  { name: 'Egham', slug: 'egham', county: 'Surrey', hub: 'guildford' },
  { name: 'Staines-upon-Thames', slug: 'staines-upon-thames', county: 'Surrey', hub: 'guildford' },
  { name: 'Virginia Water', slug: 'virginia-water', county: 'Surrey', hub: 'guildford' },
  { name: 'Chertsey', slug: 'chertsey', county: 'Surrey', hub: 'guildford' },
  { name: 'Addlestone', slug: 'addlestone', county: 'Surrey', hub: 'guildford' },
  { name: 'Weybridge', slug: 'weybridge', county: 'Surrey', hub: 'guildford' },
  { name: 'Walton-on-Thames', slug: 'walton-on-thames', county: 'Surrey', hub: 'guildford' },
  { name: 'Epsom', slug: 'epsom', county: 'Surrey', hub: 'guildford' },
  { name: 'Leatherhead', slug: 'leatherhead', county: 'Surrey', hub: 'guildford' },
  { name: 'Dorking', slug: 'dorking', county: 'Surrey', hub: 'guildford' },
  { name: 'Reigate', slug: 'reigate', county: 'Surrey', hub: 'guildford' },
  { name: 'Redhill', slug: 'redhill', county: 'Surrey', hub: 'guildford' },
  { name: 'Caterham', slug: 'caterham', county: 'Surrey', hub: 'guildford' },
  { name: 'Oxted', slug: 'oxted', county: 'Surrey', hub: 'guildford' },
  { name: 'Esher', slug: 'esher', county: 'Surrey', hub: 'guildford' },
  { name: 'Cobham', slug: 'cobham', county: 'Surrey', hub: 'guildford' },
  { name: 'Surbiton', slug: 'surbiton', county: 'Surrey', hub: 'guildford' },
  { name: 'Thames Ditton', slug: 'thames-ditton', county: 'Surrey', hub: 'guildford' },
  { name: 'East Molesey', slug: 'east-molesey', county: 'Surrey', hub: 'guildford' },
  { name: 'West Molesey', slug: 'west-molesey', county: 'Surrey', hub: 'guildford' },
  { name: 'Hinchley Wood', slug: 'hinchley-wood', county: 'Surrey', hub: 'guildford' },
  { name: 'Claygate', slug: 'claygate', county: 'Surrey', hub: 'guildford' },
  { name: 'Oxshott', slug: 'oxshott', county: 'Surrey', hub: 'guildford' },
  { name: 'Fetcham', slug: 'fetcham', county: 'Surrey', hub: 'guildford' },
  { name: 'Great Bookham', slug: 'great-bookham', county: 'Surrey', hub: 'guildford' },
  { name: 'Ashtead', slug: 'ashtead', county: 'Surrey', hub: 'guildford' },
  { name: 'Ewell', slug: 'ewell', county: 'Surrey', hub: 'guildford' },
  { name: 'Stoneleigh', slug: 'stoneleigh', county: 'Surrey', hub: 'guildford' },
  { name: 'Banstead', slug: 'banstead', county: 'Surrey', hub: 'guildford' },
  { name: 'Tadworth', slug: 'tadworth', county: 'Surrey', hub: 'guildford' },
  { name: 'Kingswood', slug: 'kingswood', county: 'Surrey', hub: 'guildford' },
  { name: 'Hersham', slug: 'hersham', county: 'Surrey', hub: 'guildford' },
  { name: 'Long Ditton', slug: 'long-ditton', county: 'Surrey', hub: 'guildford' },
  { name: 'Byfleet', slug: 'byfleet', county: 'Surrey', hub: 'guildford' },
  { name: 'West Byfleet', slug: 'west-byfleet', county: 'Surrey', hub: 'guildford' },
  { name: 'Woodham', slug: 'woodham', county: 'Surrey', hub: 'guildford' },
  { name: 'Horsell', slug: 'horsell', county: 'Surrey', hub: 'guildford' },
  { name: 'Knaphill', slug: 'knaphill', county: 'Surrey', hub: 'guildford' },
  { name: 'Bisley', slug: 'bisley', county: 'Surrey', hub: 'guildford' },
  { name: 'Chobham', slug: 'chobham', county: 'Surrey', hub: 'guildford' },
  { name: 'Windlesham', slug: 'windlesham', county: 'Surrey', hub: 'guildford' },
  { name: 'Deepcut', slug: 'deepcut', county: 'Surrey', hub: 'guildford' },
  { name: 'Mytchett', slug: 'mytchett', county: 'Surrey', hub: 'guildford' },
  { name: 'Ash Vale', slug: 'ash-vale', county: 'Surrey', hub: 'guildford' },
  { name: 'Ash', slug: 'ash', county: 'Surrey', hub: 'guildford' },
  { name: 'Normandy', slug: 'normandy', county: 'Surrey', hub: 'guildford' },
  { name: 'Pirbright', slug: 'pirbright', county: 'Surrey', hub: 'guildford' },
  { name: 'Worplesdon', slug: 'worplesdon', county: 'Surrey', hub: 'guildford' },
  { name: 'Send', slug: 'send', county: 'Surrey', hub: 'guildford' },
  { name: 'Ripley', slug: 'ripley', county: 'Surrey', hub: 'guildford' },
  { name: 'Ockham', slug: 'ockham', county: 'Surrey', hub: 'guildford' },
  { name: 'Beare Green', slug: 'beare-green', county: 'Surrey', hub: 'guildford' },
  { name: 'Holmwood', slug: 'holmwood', county: 'Surrey', hub: 'guildford' },
  { name: 'Newdigate', slug: 'newdigate', county: 'Surrey', hub: 'guildford' },
  { name: 'Capel', slug: 'capel', county: 'Surrey', hub: 'guildford' },
  { name: 'Brockham', slug: 'brockham', county: 'Surrey', hub: 'guildford' },
  { name: 'Betchworth', slug: 'betchworth', county: 'Surrey', hub: 'guildford' },
  { name: 'Lower Kingswood', slug: 'lower-kingswood', county: 'Surrey', hub: 'guildford' },
  { name: 'Merstham', slug: 'merstham', county: 'Surrey', hub: 'guildford' },
  { name: 'Bletchingley', slug: 'bletchingley', county: 'Surrey', hub: 'guildford' },
  { name: 'Godstone', slug: 'godstone', county: 'Surrey', hub: 'guildford' },
  { name: 'Tatsfield', slug: 'tatsfield', county: 'Surrey', hub: 'guildford' },
]

// ─── Basingstoke hub (north Hampshire, RG21-29 + SP)
const BASINGSTOKE_AREAS: DeliveryArea[] = [
  { name: 'Basingstoke', slug: 'basingstoke', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Tadley', slug: 'tadley', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Hook', slug: 'hook', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Whitchurch', slug: 'whitchurch', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Overton', slug: 'overton', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Odiham', slug: 'odiham', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Sherfield-on-Loddon', slug: 'sherfield-on-loddon', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Alton', slug: 'alton', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Petersfield', slug: 'petersfield', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Liss', slug: 'liss', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Liphook', slug: 'liphook', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Four Marks', slug: 'four-marks', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Bentley', slug: 'bentley', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Kingsclere', slug: 'kingsclere', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Ecchinswell', slug: 'ecchinswell', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Burghclere', slug: 'burghclere', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Old Basing', slug: 'old-basing', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Basing', slug: 'basing', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Chineham', slug: 'chineham', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Sherborne St John', slug: 'sherborne-st-john', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Oakley', slug: 'oakley', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Laverstoke', slug: 'laverstoke', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'North Waltham', slug: 'north-waltham', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Dummer', slug: 'dummer', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Kempshott', slug: 'kempshott', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Ramsdell', slug: 'ramsdell', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Monk Sherborne', slug: 'monk-sherborne', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Tunworth', slug: 'tunworth', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Upton Grey', slug: 'upton-grey', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Bramley', slug: 'bramley', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Silchester', slug: 'silchester', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Mortimer West End', slug: 'mortimer-west-end', county: 'Hampshire', hub: 'basingstoke' },
  { name: 'Stratfield Saye', slug: 'stratfield-saye', county: 'Hampshire', hub: 'basingstoke' },
]

// ─── Oxford hub (OX postcode area) — Oxfordshire
const OXFORD_AREAS: DeliveryArea[] = [
  { name: 'Oxford', slug: 'oxford', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Bicester', slug: 'bicester', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Didcot', slug: 'didcot', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Witney', slug: 'witney', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Thame', slug: 'thame', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Abingdon', slug: 'abingdon', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Wallingford', slug: 'wallingford', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Kidlington', slug: 'kidlington', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Wheatley', slug: 'wheatley', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Carterton', slug: 'carterton', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Faringdon', slug: 'faringdon', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Wantage', slug: 'wantage', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Watlington', slug: 'watlington', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Chinnor', slug: 'chinnor', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Chalgrove', slug: 'chalgrove', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Woodstock', slug: 'woodstock', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Burford', slug: 'burford', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Bampton', slug: 'bampton', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Bloxham', slug: 'bloxham', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Deddington', slug: 'deddington', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Hook Norton', slug: 'hook-norton', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Chipping Norton', slug: 'chipping-norton', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Charlbury', slug: 'charlbury', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Stonesfield', slug: 'stonesfield', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Eynsham', slug: 'eynsham', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Hanborough', slug: 'hanborough', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Long Hanborough', slug: 'long-hanborough', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Yarnton', slug: 'yarnton', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Islip', slug: 'islip', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Wood Eaton', slug: 'wood-eaton', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Benson', slug: 'benson', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Crowmarsh Gifford', slug: 'crowmarsh-gifford', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Nettlebed', slug: 'nettlebed', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Bledlow', slug: 'bledlow', county: 'Buckinghamshire', hub: 'oxford' },
  { name: 'Longwick', slug: 'longwick', county: 'Buckinghamshire', hub: 'oxford' },
  { name: 'Lewknor', slug: 'lewknor', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Postcombe', slug: 'postcombe', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Tetsworth', slug: 'tetsworth', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Horspath', slug: 'horspath', county: 'Oxfordshire', hub: 'oxford' },
  { name: 'Garsington', slug: 'garsington', county: 'Oxfordshire', hub: 'oxford' },
]

// ─── Swindon hub (SN + SP postcode areas) — Wiltshire
const SWINDON_AREAS: DeliveryArea[] = [
  { name: 'Swindon', slug: 'swindon', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Highworth', slug: 'highworth', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Wroughton', slug: 'wroughton', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Royal Wootton Bassett', slug: 'royal-wootton-bassett', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Marlborough', slug: 'marlborough', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Devizes', slug: 'devizes', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Calne', slug: 'calne', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Cricklade', slug: 'cricklade', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Salisbury', slug: 'salisbury', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Amesbury', slug: 'amesbury', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Tidworth', slug: 'tidworth', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Ludgershall', slug: 'ludgershall', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Lyneham', slug: 'lyneham', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Pewsey', slug: 'pewsey', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Upavon', slug: 'upavon', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Larkhill', slug: 'larkhill', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Bulford', slug: 'bulford', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Durrington', slug: 'durrington', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Wilton', slug: 'wilton', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Downton', slug: 'downton', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Alderbury', slug: 'alderbury', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Market Lavington', slug: 'market-lavington', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Urchfont', slug: 'urchfont', county: 'Wiltshire', hub: 'swindon' },
  { name: 'West Lavington', slug: 'west-lavington', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Seend', slug: 'seend', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Melksham', slug: 'melksham', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Trowbridge', slug: 'trowbridge', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Bradford-on-Avon', slug: 'bradford-on-avon', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Westbury', slug: 'westbury', county: 'Wiltshire', hub: 'swindon' },
  { name: 'Warminster', slug: 'warminster', county: 'Wiltshire', hub: 'swindon' },
]

// ─── London hub — Greater London boroughs + outer Middlesex
const LONDON_AREAS: DeliveryArea[] = [
  { name: 'Hounslow', slug: 'hounslow', county: 'Greater London', hub: 'london' },
  { name: 'Southall', slug: 'southall', county: 'Greater London', hub: 'london' },
  { name: 'Harrow', slug: 'harrow', county: 'Greater London', hub: 'london' },
  { name: 'Wembley', slug: 'wembley', county: 'Greater London', hub: 'london' },
  { name: 'Ealing', slug: 'ealing', county: 'Greater London', hub: 'london' },
  { name: 'Richmond', slug: 'richmond', county: 'Greater London', hub: 'london' },
  { name: 'Twickenham', slug: 'twickenham', county: 'Greater London', hub: 'london' },
  { name: 'Feltham', slug: 'feltham', county: 'Greater London', hub: 'london' },
  { name: 'Ashford', slug: 'ashford-surrey', county: 'Surrey', hub: 'london' },
  { name: 'Sunbury-on-Thames', slug: 'sunbury-on-thames', county: 'Surrey', hub: 'london' },
  { name: 'Teddington', slug: 'teddington', county: 'Greater London', hub: 'london' },
  { name: 'Hampton', slug: 'hampton', county: 'Greater London', hub: 'london' },
  { name: 'Enfield', slug: 'enfield', county: 'Greater London', hub: 'london' },
  { name: 'Croydon', slug: 'croydon', county: 'Greater London', hub: 'london' },
  { name: 'Kingston upon Thames', slug: 'kingston-upon-thames', county: 'Greater London', hub: 'london' },
  { name: 'Barnet', slug: 'barnet', county: 'Greater London', hub: 'london' },
  { name: 'Edgware', slug: 'edgware', county: 'Greater London', hub: 'london' },
  { name: 'Finchley', slug: 'finchley', county: 'Greater London', hub: 'london' },
  { name: 'Walthamstow', slug: 'walthamstow', county: 'Greater London', hub: 'london' },
  { name: 'Stratford', slug: 'stratford', county: 'Greater London', hub: 'london' },
  { name: 'Bromley', slug: 'bromley', county: 'Greater London', hub: 'london' },
  { name: 'Beckenham', slug: 'beckenham', county: 'Greater London', hub: 'london' },
  { name: 'Orpington', slug: 'orpington', county: 'Greater London', hub: 'london' },
  { name: 'Bexleyheath', slug: 'bexleyheath', county: 'Greater London', hub: 'london' },
  { name: 'Sidcup', slug: 'sidcup', county: 'Greater London', hub: 'london' },
  { name: 'Dartford', slug: 'dartford', county: 'Kent', hub: 'london' },
  { name: 'Gravesend', slug: 'gravesend', county: 'Kent', hub: 'london' },
  { name: 'Erith', slug: 'erith', county: 'Greater London', hub: 'london' },
  { name: 'Brentford', slug: 'brentford', county: 'Greater London', hub: 'london' },
  { name: 'Chiswick', slug: 'chiswick', county: 'Greater London', hub: 'london' },
  { name: 'Isleworth', slug: 'isleworth', county: 'Greater London', hub: 'london' },
  { name: 'Acton', slug: 'acton', county: 'Greater London', hub: 'london' },
  { name: 'Hanwell', slug: 'hanwell', county: 'Greater London', hub: 'london' },
  { name: 'Greenford', slug: 'greenford', county: 'Greater London', hub: 'london' },
  { name: 'Northolt', slug: 'northolt', county: 'Greater London', hub: 'london' },
  { name: 'Perivale', slug: 'perivale', county: 'Greater London', hub: 'london' },
  { name: 'Alperton', slug: 'alperton', county: 'Greater London', hub: 'london' },
  { name: 'Sudbury', slug: 'sudbury', county: 'Greater London', hub: 'london' },
  { name: 'Kenton', slug: 'kenton', county: 'Greater London', hub: 'london' },
  { name: 'Stanmore', slug: 'stanmore', county: 'Greater London', hub: 'london' },
  { name: 'Canons Park', slug: 'canons-park', county: 'Greater London', hub: 'london' },
  { name: 'Burnt Oak', slug: 'burnt-oak', county: 'Greater London', hub: 'london' },
  { name: 'Mill Hill', slug: 'mill-hill', county: 'Greater London', hub: 'london' },
  { name: 'Colindale', slug: 'colindale', county: 'Greater London', hub: 'london' },
  { name: 'Hendon', slug: 'hendon', county: 'Greater London', hub: 'london' },
  { name: 'Cricklewood', slug: 'cricklewood', county: 'Greater London', hub: 'london' },
  { name: 'Willesden', slug: 'willesden', county: 'Greater London', hub: 'london' },
  { name: 'Brent Cross', slug: 'brent-cross', county: 'Greater London', hub: 'london' },
  { name: 'Golders Green', slug: 'golders-green', county: 'Greater London', hub: 'london' },
  { name: 'Hampstead', slug: 'hampstead', county: 'Greater London', hub: 'london' },
  { name: 'Highgate', slug: 'highgate', county: 'Greater London', hub: 'london' },
  { name: 'Muswell Hill', slug: 'muswell-hill', county: 'Greater London', hub: 'london' },
  { name: 'Crouch End', slug: 'crouch-end', county: 'Greater London', hub: 'london' },
  { name: 'Hornsey', slug: 'hornsey', county: 'Greater London', hub: 'london' },
  { name: 'Wood Green', slug: 'wood-green', county: 'Greater London', hub: 'london' },
  { name: 'Tottenham', slug: 'tottenham', county: 'Greater London', hub: 'london' },
  { name: 'Edmonton', slug: 'edmonton', county: 'Greater London', hub: 'london' },
  { name: 'Southgate', slug: 'southgate', county: 'Greater London', hub: 'london' },
  { name: 'Palmers Green', slug: 'palmers-green', county: 'Greater London', hub: 'london' },
  { name: 'Winchmore Hill', slug: 'winchmore-hill', county: 'Greater London', hub: 'london' },
  { name: 'Cockfosters', slug: 'cockfosters', county: 'Greater London', hub: 'london' },
  { name: 'Hadley Wood', slug: 'hadley-wood', county: 'Greater London', hub: 'london' },
  { name: 'New Barnet', slug: 'new-barnet', county: 'Greater London', hub: 'london' },
  { name: 'Whetstone', slug: 'whetstone', county: 'Greater London', hub: 'london' },
  { name: 'Totteridge', slug: 'totteridge', county: 'Greater London', hub: 'london' },
  { name: 'Sutton', slug: 'sutton', county: 'Greater London', hub: 'london' },
  { name: 'Carshalton', slug: 'carshalton', county: 'Greater London', hub: 'london' },
  { name: 'Wallington', slug: 'wallington', county: 'Greater London', hub: 'london' },
  { name: 'Cheam', slug: 'cheam', county: 'Greater London', hub: 'london' },
  { name: 'Mitcham', slug: 'mitcham', county: 'Greater London', hub: 'london' },
  { name: 'Morden', slug: 'morden', county: 'Greater London', hub: 'london' },
  { name: 'Wimbledon', slug: 'wimbledon', county: 'Greater London', hub: 'london' },
  { name: 'Merton', slug: 'merton', county: 'Greater London', hub: 'london' },
  { name: 'Coulsdon', slug: 'coulsdon', county: 'Greater London', hub: 'london' },
  { name: 'Purley', slug: 'purley', county: 'Greater London', hub: 'london' },
  { name: 'Kenley', slug: 'kenley', county: 'Greater London', hub: 'london' },
  { name: 'Sanderstead', slug: 'sanderstead', county: 'Greater London', hub: 'london' },
  { name: 'Crystal Palace', slug: 'crystal-palace', county: 'Greater London', hub: 'london' },
  { name: 'Penge', slug: 'penge', county: 'Greater London', hub: 'london' },
  { name: 'Catford', slug: 'catford', county: 'Greater London', hub: 'london' },
  { name: 'Lewisham', slug: 'lewisham', county: 'Greater London', hub: 'london' },
  { name: 'Greenwich', slug: 'greenwich', county: 'Greater London', hub: 'london' },
  { name: 'Woolwich', slug: 'woolwich', county: 'Greater London', hub: 'london' },
  { name: 'Eltham', slug: 'eltham', county: 'Greater London', hub: 'london' },
  { name: 'Chislehurst', slug: 'chislehurst', county: 'Greater London', hub: 'london' },
  { name: 'West Wickham', slug: 'west-wickham', county: 'Greater London', hub: 'london' },
  { name: 'Biggin Hill', slug: 'biggin-hill', county: 'Greater London', hub: 'london' },
  { name: 'Keston', slug: 'keston', county: 'Greater London', hub: 'london' },
  { name: 'Hayes', slug: 'hayes-kent', county: 'Greater London', hub: 'london' },
  { name: 'Bexley', slug: 'bexley', county: 'Greater London', hub: 'london' },
  { name: 'Crayford', slug: 'crayford', county: 'Greater London', hub: 'london' },
  { name: 'Welling', slug: 'welling', county: 'Greater London', hub: 'london' },
  { name: 'Abbey Wood', slug: 'abbey-wood', county: 'Greater London', hub: 'london' },
  { name: 'East Ham', slug: 'east-ham', county: 'Greater London', hub: 'london' },
  { name: 'West Ham', slug: 'west-ham', county: 'Greater London', hub: 'london' },
  { name: 'Plaistow', slug: 'plaistow', county: 'Greater London', hub: 'london' },
  { name: 'Forest Gate', slug: 'forest-gate', county: 'Greater London', hub: 'london' },
  { name: 'Manor Park', slug: 'manor-park', county: 'Greater London', hub: 'london' },
  { name: 'Leyton', slug: 'leyton', county: 'Greater London', hub: 'london' },
  { name: 'Leytonstone', slug: 'leytonstone', county: 'Greater London', hub: 'london' },
  { name: 'Wanstead', slug: 'wanstead', county: 'Greater London', hub: 'london' },
  { name: 'Snaresbrook', slug: 'snaresbrook', county: 'Greater London', hub: 'london' },
  { name: 'Woodford', slug: 'woodford', county: 'Greater London', hub: 'london' },
  { name: 'Redbridge', slug: 'redbridge', county: 'Greater London', hub: 'london' },
  { name: 'Seven Kings', slug: 'seven-kings', county: 'Greater London', hub: 'london' },
  { name: 'Goodmayes', slug: 'goodmayes', county: 'Greater London', hub: 'london' },
  { name: 'Chadwell Heath', slug: 'chadwell-heath', county: 'Greater London', hub: 'london' },
  { name: 'Harold Hill', slug: 'harold-hill', county: 'Greater London', hub: 'london' },
  { name: 'Harold Wood', slug: 'harold-wood', county: 'Greater London', hub: 'london' },
  { name: 'Gidea Park', slug: 'gidea-park', county: 'Greater London', hub: 'london' },
  { name: 'Collier Row', slug: 'collier-row', county: 'Greater London', hub: 'london' },
  { name: 'Chingford', slug: 'chingford', county: 'Greater London', hub: 'london' },
  { name: 'Highams Park', slug: 'highams-park', county: 'Greater London', hub: 'london' },
]

// ─── Luton hub (LU + AL + SG south) — Bedfordshire + Hertfordshire
const LUTON_AREAS: DeliveryArea[] = [
  { name: 'Luton', slug: 'luton', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Dunstable', slug: 'dunstable', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Leighton Buzzard', slug: 'leighton-buzzard', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Toddington', slug: 'toddington', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Ampthill', slug: 'ampthill', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Flitwick', slug: 'flitwick', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Caddington', slug: 'caddington', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Harpenden', slug: 'harpenden', county: 'Hertfordshire', hub: 'luton' },
  { name: 'St Albans', slug: 'st-albans', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Wheathampstead', slug: 'wheathampstead', county: 'Hertfordshire', hub: 'luton' },
  { name: 'London Colney', slug: 'london-colney', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Hatfield', slug: 'hatfield', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Welwyn Garden City', slug: 'welwyn-garden-city', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Potters Bar', slug: 'potters-bar', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Hertford', slug: 'hertford', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Ware', slug: 'ware', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Hoddesdon', slug: 'hoddesdon', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Cheshunt', slug: 'cheshunt', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Waltham Cross', slug: 'waltham-cross', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Waltham Abbey', slug: 'waltham-abbey', county: 'Essex', hub: 'luton' },
  { name: 'Hemel Hempstead', slug: 'hemel-hempstead', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Berkhamsted', slug: 'berkhamsted', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Tring', slug: 'tring', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Stevenage', slug: 'stevenage', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Hitchin', slug: 'hitchin', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Letchworth', slug: 'letchworth', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Baldock', slug: 'baldock', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Royston', slug: 'royston', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Biggleswade', slug: 'biggleswade', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Sandy', slug: 'sandy', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Bedford', slug: 'bedford', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Kempston', slug: 'kempston', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Milton Keynes', slug: 'milton-keynes', county: 'Buckinghamshire', hub: 'luton' },
  { name: 'Bletchley', slug: 'bletchley', county: 'Buckinghamshire', hub: 'luton' },
  { name: 'Newport Pagnell', slug: 'newport-pagnell', county: 'Buckinghamshire', hub: 'luton' },
  { name: 'Wolverton', slug: 'wolverton', county: 'Buckinghamshire', hub: 'luton' },
  { name: 'Stony Stratford', slug: 'stony-stratford', county: 'Buckinghamshire', hub: 'luton' },
  { name: 'Watford', slug: 'watford', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Rickmansworth', slug: 'rickmansworth', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Bushey', slug: 'bushey', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Borehamwood', slug: 'borehamwood', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Radlett', slug: 'radlett', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Chorleywood', slug: 'chorleywood', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Broxbourne', slug: 'broxbourne', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Cuffley', slug: 'cuffley', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Goffs Oak', slug: 'goffs-oak', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Bayford', slug: 'bayford', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Brickendon', slug: 'brickendon', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Tewin', slug: 'tewin', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Datchworth', slug: 'datchworth', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Watton-at-Stone', slug: 'watton-at-stone', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Benington', slug: 'benington', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Bramfield', slug: 'bramfield', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Knebworth', slug: 'knebworth', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Codicote', slug: 'codicote', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Welwyn', slug: 'welwyn', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Oaklands', slug: 'oaklands', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Woolmer Green', slug: 'woolmer-green', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Kimpton', slug: 'kimpton', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Markyate', slug: 'markyate', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Flamstead', slug: 'flamstead', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Redbourn', slug: 'redbourn', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Park Street', slug: 'park-street', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Bricket Wood', slug: 'bricket-wood', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Colney Heath', slug: 'colney-heath', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Smallford', slug: 'smallford', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Essendon', slug: 'essendon', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Little Berkhamsted', slug: 'little-berkhamsted', county: 'Hertfordshire', hub: 'luton' },
  { name: 'North Mymms', slug: 'north-mymms', county: 'Hertfordshire', hub: 'luton' },
  { name: 'South Mimms', slug: 'south-mimms', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Sarratt', slug: 'sarratt', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Chipperfield', slug: 'chipperfield', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Bovingdon', slug: 'bovingdon', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Kings Langley', slug: 'kings-langley', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Apsley', slug: 'apsley', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Boxmoor', slug: 'boxmoor', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Holwell', slug: 'holwell', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Pirton', slug: 'pirton', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Shillington', slug: 'shillington', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Henlow', slug: 'henlow', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Langford', slug: 'langford', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Shefford', slug: 'shefford', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Clifton', slug: 'clifton', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Arlesey', slug: 'arlesey', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Stotfold', slug: 'stotfold', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Meppershall', slug: 'meppershall', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Chicksands', slug: 'chicksands', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Barton-le-Clay', slug: 'barton-le-clay', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Hexton', slug: 'hexton', county: 'Hertfordshire', hub: 'luton' },
  { name: 'Barton Hills', slug: 'barton-hills', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Sundon', slug: 'sundon', county: 'Bedfordshire', hub: 'luton' },
  { name: 'Streatley', slug: 'streatley-beds', county: 'Bedfordshire', hub: 'luton' },
]

// ─── Southend hub (CM + SS post towns) — Essex
const SOUTHEND_AREAS: DeliveryArea[] = [
  { name: 'Chelmsford', slug: 'chelmsford', county: 'Essex', hub: 'southend' },
  { name: 'Brentwood', slug: 'brentwood', county: 'Essex', hub: 'southend' },
  { name: 'Billericay', slug: 'billericay', county: 'Essex', hub: 'southend' },
  { name: 'Ingatestone', slug: 'ingatestone', county: 'Essex', hub: 'southend' },
  { name: 'Writtle', slug: 'writtle', county: 'Essex', hub: 'southend' },
  { name: 'Southend-on-Sea', slug: 'southend-on-sea', county: 'Essex', hub: 'southend' },
  { name: 'Leigh-on-Sea', slug: 'leigh-on-sea', county: 'Essex', hub: 'southend' },
  { name: 'Westcliff-on-Sea', slug: 'westcliff-on-sea', county: 'Essex', hub: 'southend' },
  { name: 'Rayleigh', slug: 'rayleigh', county: 'Essex', hub: 'southend' },
  { name: 'Rochford', slug: 'rochford', county: 'Essex', hub: 'southend' },
  { name: 'Hockley', slug: 'hockley', county: 'Essex', hub: 'southend' },
  { name: 'Basildon', slug: 'basildon', county: 'Essex', hub: 'southend' },
  { name: 'Wickford', slug: 'wickford', county: 'Essex', hub: 'southend' },
  { name: 'Canvey Island', slug: 'canvey-island', county: 'Essex', hub: 'southend' },
  { name: 'Benfleet', slug: 'benfleet', county: 'Essex', hub: 'southend' },
  { name: 'Harlow', slug: 'harlow', county: 'Essex', hub: 'southend' },
  { name: 'Bishop\u2019s Stortford', slug: 'bishops-stortford', county: 'Hertfordshire', hub: 'southend' },
  { name: 'Sawbridgeworth', slug: 'sawbridgeworth', county: 'Hertfordshire', hub: 'southend' },
  { name: 'Epping', slug: 'epping', county: 'Essex', hub: 'southend' },
  { name: 'Loughton', slug: 'loughton', county: 'Essex', hub: 'southend' },
  { name: 'Buckhurst Hill', slug: 'buckhurst-hill', county: 'Essex', hub: 'southend' },
  { name: 'Chigwell', slug: 'chigwell', county: 'Essex', hub: 'southend' },
  { name: 'Romford', slug: 'romford', county: 'Greater London', hub: 'southend' },
  { name: 'Hornchurch', slug: 'hornchurch', county: 'Greater London', hub: 'southend' },
  { name: 'Upminster', slug: 'upminster', county: 'Greater London', hub: 'southend' },
  { name: 'Rainham', slug: 'rainham', county: 'Greater London', hub: 'southend' },
  { name: 'Ilford', slug: 'ilford', county: 'Greater London', hub: 'southend' },
  { name: 'Dagenham', slug: 'dagenham', county: 'Greater London', hub: 'southend' },
  { name: 'Stansted Mountfitchet', slug: 'stansted-mountfitchet', county: 'Essex', hub: 'southend' },
  { name: 'Takeley', slug: 'takeley', county: 'Essex', hub: 'southend' },
  { name: 'Hatfield Heath', slug: 'hatfield-heath', county: 'Essex', hub: 'southend' },
  { name: 'Hatfield Broad Oak', slug: 'hatfield-broad-oak', county: 'Essex', hub: 'southend' },
  { name: 'Stock', slug: 'stock', county: 'Essex', hub: 'southend' },
  { name: 'Danbury', slug: 'danbury', county: 'Essex', hub: 'southend' },
  { name: 'Maldon', slug: 'maldon', county: 'Essex', hub: 'southend' },
  { name: 'Heybridge', slug: 'heybridge', county: 'Essex', hub: 'southend' },
  { name: 'Witham', slug: 'witham', county: 'Essex', hub: 'southend' },
  { name: 'Kelvedon', slug: 'kelvedon', county: 'Essex', hub: 'southend' },
  { name: 'Coggeshall', slug: 'coggeshall', county: 'Essex', hub: 'southend' },
  { name: 'Colchester', slug: 'colchester', county: 'Essex', hub: 'southend' },
  { name: 'Wivenhoe', slug: 'wivenhoe', county: 'Essex', hub: 'southend' },
  { name: 'Manningtree', slug: 'manningtree', county: 'Essex', hub: 'southend' },
  { name: 'Harwich', slug: 'harwich', county: 'Essex', hub: 'southend' },
  { name: 'Chipping Ongar', slug: 'chipping-ongar', county: 'Essex', hub: 'southend' },
  { name: 'Ongar', slug: 'ongar', county: 'Essex', hub: 'southend' },
  { name: 'North Weald', slug: 'north-weald', county: 'Essex', hub: 'southend' },
  { name: 'Theydon Bois', slug: 'theydon-bois', county: 'Essex', hub: 'southend' },
  { name: 'Debden', slug: 'debden', county: 'Essex', hub: 'southend' },
  { name: 'Shenfield', slug: 'shenfield', county: 'Essex', hub: 'southend' },
  { name: 'Hutton', slug: 'hutton', county: 'Essex', hub: 'southend' },
  { name: 'Mountnessing', slug: 'mountnessing', county: 'Essex', hub: 'southend' },
  { name: 'Burnham-on-Crouch', slug: 'burnham-on-crouch', county: 'Essex', hub: 'southend' },
  { name: 'Southminster', slug: 'southminster', county: 'Essex', hub: 'southend' },
]

// ─── Maidstone hub (ME + TN west) — Kent
const MAIDSTONE_AREAS: DeliveryArea[] = [
  { name: 'Maidstone', slug: 'maidstone', county: 'Kent', hub: 'maidstone' },
  { name: 'Rochester', slug: 'rochester', county: 'Kent', hub: 'maidstone' },
  { name: 'Chatham', slug: 'chatham', county: 'Kent', hub: 'maidstone' },
  { name: 'Gillingham', slug: 'gillingham', county: 'Kent', hub: 'maidstone' },
  { name: 'Strood', slug: 'strood', county: 'Kent', hub: 'maidstone' },
  { name: 'Sittingbourne', slug: 'sittingbourne', county: 'Kent', hub: 'maidstone' },
  { name: 'Sheerness', slug: 'sheerness', county: 'Kent', hub: 'maidstone' },
  { name: 'Sevenoaks', slug: 'sevenoaks', county: 'Kent', hub: 'maidstone' },
  { name: 'Westerham', slug: 'westerham', county: 'Kent', hub: 'maidstone' },
  { name: 'Edenbridge', slug: 'edenbridge', county: 'Kent', hub: 'maidstone' },
  { name: 'Tonbridge', slug: 'tonbridge', county: 'Kent', hub: 'maidstone' },
  { name: 'Royal Tunbridge Wells', slug: 'tunbridge-wells', county: 'Kent', hub: 'maidstone' },
  { name: 'Southborough', slug: 'southborough', county: 'Kent', hub: 'maidstone' },
  { name: 'Paddock Wood', slug: 'paddock-wood', county: 'Kent', hub: 'maidstone' },
  { name: 'Cranbrook', slug: 'cranbrook', county: 'Kent', hub: 'maidstone' },
  { name: 'Ashford', slug: 'ashford', county: 'Kent', hub: 'maidstone' },
  { name: 'Folkestone', slug: 'folkestone', county: 'Kent', hub: 'maidstone' },
  { name: 'Canterbury', slug: 'canterbury', county: 'Kent', hub: 'maidstone' },
  { name: 'Whitstable', slug: 'whitstable', county: 'Kent', hub: 'maidstone' },
  { name: 'Dover', slug: 'dover', county: 'Kent', hub: 'maidstone' },
  { name: 'Deal', slug: 'deal', county: 'Kent', hub: 'maidstone' },
  { name: 'Sandwich', slug: 'sandwich', county: 'Kent', hub: 'maidstone' },
  { name: 'Margate', slug: 'margate', county: 'Kent', hub: 'maidstone' },
  { name: 'Ramsgate', slug: 'ramsgate', county: 'Kent', hub: 'maidstone' },
  { name: 'Broadstairs', slug: 'broadstairs', county: 'Kent', hub: 'maidstone' },
  { name: 'Birchington-on-Sea', slug: 'birchington-on-sea', county: 'Kent', hub: 'maidstone' },
  { name: 'Westgate-on-Sea', slug: 'westgate-on-sea', county: 'Kent', hub: 'maidstone' },
  { name: 'Herne Bay', slug: 'herne-bay', county: 'Kent', hub: 'maidstone' },
  { name: 'Faversham', slug: 'faversham', county: 'Kent', hub: 'maidstone' },
  { name: 'Tenterden', slug: 'tenterden', county: 'Kent', hub: 'maidstone' },
  { name: 'New Romney', slug: 'new-romney', county: 'Kent', hub: 'maidstone' },
  { name: 'Lydd', slug: 'lydd', county: 'Kent', hub: 'maidstone' },
  { name: 'Hythe', slug: 'hythe-kent', county: 'Kent', hub: 'maidstone' },
  { name: 'Dymchurch', slug: 'dymchurch', county: 'Kent', hub: 'maidstone' },
  { name: 'Headcorn', slug: 'headcorn', county: 'Kent', hub: 'maidstone' },
  { name: 'Staplehurst', slug: 'staplehurst', county: 'Kent', hub: 'maidstone' },
  { name: 'Marden', slug: 'marden', county: 'Kent', hub: 'maidstone' },
  { name: 'Yalding', slug: 'yalding', county: 'Kent', hub: 'maidstone' },
  { name: 'Bidborough', slug: 'bidborough', county: 'Kent', hub: 'maidstone' },
  { name: 'Speldhurst', slug: 'speldhurst', county: 'Kent', hub: 'maidstone' },
  { name: 'Langton Green', slug: 'langton-green', county: 'Kent', hub: 'maidstone' },
  { name: 'Groombridge', slug: 'groombridge', county: 'Kent', hub: 'maidstone' },
  { name: 'Lamberhurst', slug: 'lamberhurst', county: 'Kent', hub: 'maidstone' },
  { name: 'Horsmonden', slug: 'horsmonden', county: 'Kent', hub: 'maidstone' },
  { name: 'Biddenden', slug: 'biddenden', county: 'Kent', hub: 'maidstone' },
  { name: 'Benenden', slug: 'benenden', county: 'Kent', hub: 'maidstone' },
  { name: 'Sandhurst', slug: 'sandhurst-kent', county: 'Kent', hub: 'maidstone' },
  { name: 'Northiam', slug: 'northiam', county: 'East Sussex', hub: 'maidstone' },
  { name: 'Beckley', slug: 'beckley', county: 'East Sussex', hub: 'maidstone' },
  { name: 'Peasmarsh', slug: 'peasmarsh', county: 'East Sussex', hub: 'maidstone' },
  { name: 'Rye', slug: 'rye', county: 'East Sussex', hub: 'maidstone' },
  { name: 'Rye Harbour', slug: 'rye-harbour', county: 'East Sussex', hub: 'maidstone' },
  { name: 'Playden', slug: 'playden', county: 'East Sussex', hub: 'maidstone' },
  { name: 'Iden', slug: 'iden', county: 'East Sussex', hub: 'maidstone' },
  { name: 'Brookland', slug: 'brookland', county: 'Kent', hub: 'maidstone' },
  { name: 'Appledore', slug: 'appledore', county: 'Kent', hub: 'maidstone' },
  { name: 'Woodchurch', slug: 'woodchurch', county: 'Kent', hub: 'maidstone' },
  { name: 'Hamstreet', slug: 'hamstreet', county: 'Kent', hub: 'maidstone' },
  { name: 'Aldington', slug: 'aldington', county: 'Kent', hub: 'maidstone' },
  { name: 'Wye', slug: 'wye', county: 'Kent', hub: 'maidstone' },
  { name: 'Chilham', slug: 'chilham', county: 'Kent', hub: 'maidstone' },
  { name: 'Chartham', slug: 'chartham', county: 'Kent', hub: 'maidstone' },
  { name: 'Bearsted', slug: 'bearsted', county: 'Kent', hub: 'maidstone' },
  { name: 'Aylesford', slug: 'aylesford', county: 'Kent', hub: 'maidstone' },
  { name: 'Snodland', slug: 'snodland', county: 'Kent', hub: 'maidstone' },
  { name: 'West Malling', slug: 'west-malling', county: 'Kent', hub: 'maidstone' },
  { name: 'East Malling', slug: 'east-malling', county: 'Kent', hub: 'maidstone' },
  { name: 'Larkfield', slug: 'larkfield', county: 'Kent', hub: 'maidstone' },
  { name: 'Ditton', slug: 'ditton', county: 'Kent', hub: 'maidstone' },
  { name: 'Cuxton', slug: 'cuxton', county: 'Kent', hub: 'maidstone' },
  { name: 'Hoo', slug: 'hoo', county: 'Kent', hub: 'maidstone' },
  { name: 'Higham', slug: 'higham', county: 'Kent', hub: 'maidstone' },
  { name: 'Cliffe', slug: 'cliffe', county: 'Kent', hub: 'maidstone' },
  { name: 'Isle of Grain', slug: 'isle-of-grain', county: 'Kent', hub: 'maidstone' },
  { name: 'Queenborough', slug: 'queenborough', county: 'Kent', hub: 'maidstone' },
  { name: 'Minster', slug: 'minster', county: 'Kent', hub: 'maidstone' },
  { name: 'Lenham', slug: 'lenham', county: 'Kent', hub: 'maidstone' },
  { name: 'Harrietsham', slug: 'harrietsham', county: 'Kent', hub: 'maidstone' },
  { name: 'Hollingbourne', slug: 'hollingbourne', county: 'Kent', hub: 'maidstone' },
  { name: 'Boxley', slug: 'boxley', county: 'Kent', hub: 'maidstone' },
  { name: 'Pluckley', slug: 'pluckley', county: 'Kent', hub: 'maidstone' },
  { name: 'Egerton', slug: 'egerton', county: 'Kent', hub: 'maidstone' },
  { name: 'Smarden', slug: 'smarden', county: 'Kent', hub: 'maidstone' },
  { name: 'Boughton Malherbe', slug: 'boughton-malherbe', county: 'Kent', hub: 'maidstone' },
  { name: 'Kingsnorth', slug: 'kingsnorth', county: 'Kent', hub: 'maidstone' },
  { name: 'Mersham', slug: 'mersham', county: 'Kent', hub: 'maidstone' },
  { name: 'Smeeth', slug: 'smeeth', county: 'Kent', hub: 'maidstone' },
  { name: 'Sellindge', slug: 'sellindge', county: 'Kent', hub: 'maidstone' },
  { name: 'Lympne', slug: 'lympne', county: 'Kent', hub: 'maidstone' },
  { name: 'Sandgate', slug: 'sandgate', county: 'Kent', hub: 'maidstone' },
  { name: 'Capel-le-Ferne', slug: 'capel-le-ferne', county: 'Kent', hub: 'maidstone' },
  { name: 'Hawkinge', slug: 'hawkinge', county: 'Kent', hub: 'maidstone' },
  { name: 'Elham', slug: 'elham', county: 'Kent', hub: 'maidstone' },
  { name: 'Lyminge', slug: 'lyminge', county: 'Kent', hub: 'maidstone' },
  { name: 'Shepherdswell', slug: 'shepherdswell', county: 'Kent', hub: 'maidstone' },
  { name: 'Eastry', slug: 'eastry', county: 'Kent', hub: 'maidstone' },
  { name: 'Wrotham', slug: 'wrotham', county: 'Kent', hub: 'maidstone' },
  { name: 'Ightham', slug: 'ightham', county: 'Kent', hub: 'maidstone' },
  { name: 'Borough Green', slug: 'borough-green', county: 'Kent', hub: 'maidstone' },
  { name: 'Wrotham Heath', slug: 'wrotham-heath', county: 'Kent', hub: 'maidstone' },
  { name: 'Kemsing', slug: 'kemsing', county: 'Kent', hub: 'maidstone' },
  { name: 'Otford', slug: 'otford', county: 'Kent', hub: 'maidstone' },
  { name: 'Shoreham', slug: 'shoreham', county: 'Kent', hub: 'maidstone' },
  { name: 'Eynsford', slug: 'eynsford', county: 'Kent', hub: 'maidstone' },
  { name: 'Farningham', slug: 'farningham', county: 'Kent', hub: 'maidstone' },
  { name: 'Swanley', slug: 'swanley', county: 'Kent', hub: 'maidstone' },
  { name: 'Hextable', slug: 'hextable', county: 'Kent', hub: 'maidstone' },
  { name: 'Crockenhill', slug: 'crockenhill', county: 'Kent', hub: 'maidstone' },
]

// ─── Brighton hub (RH + BN + CR south) — Sussex
const BRIGHTON_AREAS: DeliveryArea[] = [
  { name: 'Crawley', slug: 'crawley', county: 'West Sussex', hub: 'brighton' },
  { name: 'Horley', slug: 'horley', county: 'Surrey', hub: 'brighton' },
  { name: 'Gatwick', slug: 'gatwick', county: 'West Sussex', hub: 'brighton' },
  { name: 'East Grinstead', slug: 'east-grinstead', county: 'West Sussex', hub: 'brighton' },
  { name: 'Haywards Heath', slug: 'haywards-heath', county: 'West Sussex', hub: 'brighton' },
  { name: 'Burgess Hill', slug: 'burgess-hill', county: 'West Sussex', hub: 'brighton' },
  { name: 'Hassocks', slug: 'hassocks', county: 'West Sussex', hub: 'brighton' },
  { name: 'Horsham', slug: 'horsham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Billingshurst', slug: 'billingshurst', county: 'West Sussex', hub: 'brighton' },
  { name: 'Steyning', slug: 'steyning', county: 'West Sussex', hub: 'brighton' },
  { name: 'Brighton', slug: 'brighton', county: 'East Sussex', hub: 'brighton' },
  { name: 'Hove', slug: 'hove', county: 'East Sussex', hub: 'brighton' },
  { name: 'Lewes', slug: 'lewes', county: 'East Sussex', hub: 'brighton' },
  { name: 'Newhaven', slug: 'newhaven', county: 'East Sussex', hub: 'brighton' },
  { name: 'Peacehaven', slug: 'peacehaven', county: 'East Sussex', hub: 'brighton' },
  { name: 'Seaford', slug: 'seaford', county: 'East Sussex', hub: 'brighton' },
  { name: 'Worthing', slug: 'worthing', county: 'West Sussex', hub: 'brighton' },
  { name: 'Littlehampton', slug: 'littlehampton', county: 'West Sussex', hub: 'brighton' },
  { name: 'Bognor Regis', slug: 'bognor-regis', county: 'West Sussex', hub: 'brighton' },
  { name: 'Chichester', slug: 'chichester', county: 'West Sussex', hub: 'brighton' },
  { name: 'Uckfield', slug: 'uckfield', county: 'East Sussex', hub: 'brighton' },
  { name: 'Crowborough', slug: 'crowborough', county: 'East Sussex', hub: 'brighton' },
  { name: 'Eastbourne', slug: 'eastbourne', county: 'East Sussex', hub: 'brighton' },
  { name: 'Hastings', slug: 'hastings', county: 'East Sussex', hub: 'brighton' },
  { name: 'Bexhill', slug: 'bexhill', county: 'East Sussex', hub: 'brighton' },
  { name: 'Bexhill-on-Sea', slug: 'bexhill-on-sea', county: 'East Sussex', hub: 'brighton' },
  { name: 'Battle', slug: 'battle', county: 'East Sussex', hub: 'brighton' },
  { name: 'Ninfield', slug: 'ninfield', county: 'East Sussex', hub: 'brighton' },
  { name: 'Heathfield', slug: 'heathfield', county: 'East Sussex', hub: 'brighton' },
  { name: 'Horam', slug: 'horam', county: 'East Sussex', hub: 'brighton' },
  { name: 'Mayfield', slug: 'mayfield', county: 'East Sussex', hub: 'brighton' },
  { name: 'Rotherfield', slug: 'rotherfield', county: 'East Sussex', hub: 'brighton' },
  { name: 'Wadhurst', slug: 'wadhurst', county: 'East Sussex', hub: 'brighton' },
  { name: 'Ticehurst', slug: 'ticehurst', county: 'East Sussex', hub: 'brighton' },
  { name: 'Etchingham', slug: 'etchingham', county: 'East Sussex', hub: 'brighton' },
  { name: 'Burwash', slug: 'burwash', county: 'East Sussex', hub: 'brighton' },
  { name: 'Robertsbridge', slug: 'robertsbridge', county: 'East Sussex', hub: 'brighton' },
  { name: 'Hailsham', slug: 'hailsham', county: 'East Sussex', hub: 'brighton' },
  { name: 'Polegate', slug: 'polegate', county: 'East Sussex', hub: 'brighton' },
  { name: 'Pevensey', slug: 'pevensey', county: 'East Sussex', hub: 'brighton' },
  { name: 'Pevensey Bay', slug: 'pevensey-bay', county: 'East Sussex', hub: 'brighton' },
  { name: 'Westham', slug: 'westham', county: 'East Sussex', hub: 'brighton' },
  { name: 'Stone Cross', slug: 'stone-cross', county: 'East Sussex', hub: 'brighton' },
  { name: 'Langney', slug: 'langney', county: 'East Sussex', hub: 'brighton' },
  { name: 'Hampden Park', slug: 'hampden-park', county: 'East Sussex', hub: 'brighton' },
  { name: 'Willingdon', slug: 'willingdon', county: 'East Sussex', hub: 'brighton' },
  { name: 'Alfriston', slug: 'alfriston', county: 'East Sussex', hub: 'brighton' },
  { name: 'West Dean', slug: 'west-dean', county: 'East Sussex', hub: 'brighton' },
  { name: 'Ringmer', slug: 'ringmer', county: 'East Sussex', hub: 'brighton' },
  { name: 'Glynde', slug: 'glynde', county: 'East Sussex', hub: 'brighton' },
  { name: 'Rodmell', slug: 'rodmell', county: 'East Sussex', hub: 'brighton' },
  { name: 'Isfield', slug: 'isfield', county: 'East Sussex', hub: 'brighton' },
  { name: 'Buxted', slug: 'buxted', county: 'East Sussex', hub: 'brighton' },
  { name: 'Hadlow Down', slug: 'hadlow-down', county: 'East Sussex', hub: 'brighton' },
  { name: 'Five Ashes', slug: 'five-ashes', county: 'East Sussex', hub: 'brighton' },
  { name: 'Cross in Hand', slug: 'cross-in-hand', county: 'East Sussex', hub: 'brighton' },
  { name: 'Staplecross', slug: 'staplecross', county: 'East Sussex', hub: 'brighton' },
  { name: 'Bodiam', slug: 'bodiam', county: 'East Sussex', hub: 'brighton' },
  { name: 'Camber', slug: 'camber', county: 'East Sussex', hub: 'brighton' },
  { name: 'Winchelsea', slug: 'winchelsea', county: 'East Sussex', hub: 'brighton' },
  { name: 'Winchelsea Beach', slug: 'winchelsea-beach', county: 'East Sussex', hub: 'brighton' },
  { name: 'Icklesham', slug: 'icklesham', county: 'East Sussex', hub: 'brighton' },
  { name: 'Pett', slug: 'pett', county: 'East Sussex', hub: 'brighton' },
  { name: 'Fairlight', slug: 'fairlight', county: 'East Sussex', hub: 'brighton' },
  { name: 'Ore', slug: 'ore', county: 'East Sussex', hub: 'brighton' },
  { name: 'St Leonards', slug: 'st-leonards', county: 'East Sussex', hub: 'brighton' },
  { name: 'St Leonards-on-Sea', slug: 'st-leonards-on-sea', county: 'East Sussex', hub: 'brighton' },
  { name: 'Hollington', slug: 'hollington', county: 'East Sussex', hub: 'brighton' },
  { name: 'Midhurst', slug: 'midhurst', county: 'West Sussex', hub: 'brighton' },
  { name: 'Petworth', slug: 'petworth', county: 'West Sussex', hub: 'brighton' },
  { name: 'Hindhead', slug: 'hindhead', county: 'Surrey', hub: 'brighton' },
  { name: 'Fernhurst', slug: 'fernhurst', county: 'West Sussex', hub: 'brighton' },
  { name: 'Lurgashall', slug: 'lurgashall', county: 'West Sussex', hub: 'brighton' },
  { name: 'Graffham', slug: 'graffham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Duncton', slug: 'duncton', county: 'West Sussex', hub: 'brighton' },
  { name: 'Pulborough', slug: 'pulborough', county: 'West Sussex', hub: 'brighton' },
  { name: 'Storrington', slug: 'storrington', county: 'West Sussex', hub: 'brighton' },
  { name: 'Washington', slug: 'washington', county: 'West Sussex', hub: 'brighton' },
  { name: 'Ashington', slug: 'ashington', county: 'West Sussex', hub: 'brighton' },
  { name: 'Findon', slug: 'findon', county: 'West Sussex', hub: 'brighton' },
  { name: 'Clapham', slug: 'clapham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Wisborough Green', slug: 'wisborough-green', county: 'West Sussex', hub: 'brighton' },
  { name: 'Kirdford', slug: 'kirdford', county: 'West Sussex', hub: 'brighton' },
  { name: 'Loxwood', slug: 'loxwood', county: 'West Sussex', hub: 'brighton' },
  { name: 'Alfold', slug: 'alfold', county: 'Surrey', hub: 'brighton' },
  { name: 'Ewhurst', slug: 'ewhurst', county: 'Surrey', hub: 'brighton' },
  { name: 'Rudgwick', slug: 'rudgwick', county: 'West Sussex', hub: 'brighton' },
  { name: 'Slinfold', slug: 'slinfold', county: 'West Sussex', hub: 'brighton' },
  { name: 'Barns Green', slug: 'barns-green', county: 'West Sussex', hub: 'brighton' },
  { name: 'Itchingfield', slug: 'itchingfield', county: 'West Sussex', hub: 'brighton' },
  { name: 'Broadbridge Heath', slug: 'broadbridge-heath', county: 'West Sussex', hub: 'brighton' },
  { name: 'Warnham', slug: 'warnham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Rusper', slug: 'rusper', county: 'West Sussex', hub: 'brighton' },
  { name: 'Faygate', slug: 'faygate', county: 'West Sussex', hub: 'brighton' },
  { name: 'Colgate', slug: 'colgate', county: 'West Sussex', hub: 'brighton' },
  { name: 'Handcross', slug: 'handcross', county: 'West Sussex', hub: 'brighton' },
  { name: 'Slaugham', slug: 'slaugham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Bolney', slug: 'bolney', county: 'West Sussex', hub: 'brighton' },
  { name: 'Twineham', slug: 'twineham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Albourne', slug: 'albourne', county: 'West Sussex', hub: 'brighton' },
  { name: 'Henfield', slug: 'henfield', county: 'West Sussex', hub: 'brighton' },
  { name: 'Shermanbury', slug: 'shermanbury', county: 'West Sussex', hub: 'brighton' },
  { name: 'Partridge Green', slug: 'partridge-green', county: 'West Sussex', hub: 'brighton' },
  { name: 'Cowfold', slug: 'cowfold', county: 'West Sussex', hub: 'brighton' },
  { name: 'West Grinstead', slug: 'west-grinstead', county: 'West Sussex', hub: 'brighton' },
  { name: 'Shipley', slug: 'shipley', county: 'West Sussex', hub: 'brighton' },
  { name: 'Thakeham', slug: 'thakeham', county: 'West Sussex', hub: 'brighton' },
  { name: 'West Chiltington', slug: 'west-chiltington', county: 'West Sussex', hub: 'brighton' },
  { name: 'West Wittering', slug: 'west-wittering', county: 'West Sussex', hub: 'brighton' },
  { name: 'East Wittering', slug: 'east-wittering', county: 'West Sussex', hub: 'brighton' },
  { name: 'Bracklesham', slug: 'bracklesham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Selsey', slug: 'selsey', county: 'West Sussex', hub: 'brighton' },
  { name: 'Sidlesham', slug: 'sidlesham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Birdham', slug: 'birdham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Bosham', slug: 'bosham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Fishbourne', slug: 'fishbourne', county: 'West Sussex', hub: 'brighton' },
  { name: 'Funtington', slug: 'funtington', county: 'West Sussex', hub: 'brighton' },
  { name: 'Westbourne', slug: 'westbourne', county: 'West Sussex', hub: 'brighton' },
  { name: 'Singleton', slug: 'singleton', county: 'West Sussex', hub: 'brighton' },
  { name: 'Cocking', slug: 'cocking', county: 'West Sussex', hub: 'brighton' },
  { name: 'Bepton', slug: 'bepton', county: 'West Sussex', hub: 'brighton' },
  { name: 'Elsted', slug: 'elsted', county: 'West Sussex', hub: 'brighton' },
  { name: 'Heyshott', slug: 'heyshott', county: 'West Sussex', hub: 'brighton' },
  { name: 'Amberley', slug: 'amberley', county: 'West Sussex', hub: 'brighton' },
  { name: 'Coldwaltham', slug: 'coldwaltham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Bury', slug: 'bury', county: 'West Sussex', hub: 'brighton' },
  { name: 'Fittleworth', slug: 'fittleworth', county: 'West Sussex', hub: 'brighton' },
  { name: 'Lodsworth', slug: 'lodsworth', county: 'West Sussex', hub: 'brighton' },
  { name: 'Stedham', slug: 'stedham', county: 'West Sussex', hub: 'brighton' },
  { name: 'Iping', slug: 'iping', county: 'West Sussex', hub: 'brighton' },
  { name: 'Rogate', slug: 'rogate', county: 'West Sussex', hub: 'brighton' },
  { name: 'Milland', slug: 'milland', county: 'West Sussex', hub: 'brighton' },
  { name: 'Bramshott', slug: 'bramshott', county: 'Hampshire', hub: 'brighton' },
  { name: 'Headley', slug: 'headley', county: 'Hampshire', hub: 'brighton' },
  { name: 'Headley Down', slug: 'headley-down', county: 'Hampshire', hub: 'brighton' },
  { name: 'Churt', slug: 'churt', county: 'Surrey', hub: 'brighton' },
  { name: 'Wrecclesham', slug: 'wrecclesham', county: 'Surrey', hub: 'brighton' },
  { name: 'Frensham', slug: 'frensham', county: 'Surrey', hub: 'brighton' },
  { name: 'Seale', slug: 'seale', county: 'Surrey', hub: 'brighton' },
  { name: 'Puttenham', slug: 'puttenham', county: 'Surrey', hub: 'brighton' },
  { name: 'Shamley Green', slug: 'shamley-green', county: 'Surrey', hub: 'brighton' },
  { name: 'Ockley', slug: 'ockley', county: 'Surrey', hub: 'brighton' },
  { name: 'Forest Green', slug: 'forest-green', county: 'Surrey', hub: 'brighton' },
  { name: 'Coldharbour', slug: 'coldharbour', county: 'Surrey', hub: 'brighton' },
  { name: 'Abinger', slug: 'abinger', county: 'Surrey', hub: 'brighton' },
  { name: 'Wotton', slug: 'wotton', county: 'Surrey', hub: 'brighton' },
  { name: 'Walton on the Hill', slug: 'walton-on-the-hill', county: 'Surrey', hub: 'brighton' },
  { name: 'Box Hill', slug: 'box-hill', county: 'Surrey', hub: 'brighton' },
  { name: 'Nutfield', slug: 'nutfield', county: 'Surrey', hub: 'brighton' },
  { name: 'Lingfield', slug: 'lingfield', county: 'Surrey', hub: 'brighton' },
  { name: 'Dormansland', slug: 'dormansland', county: 'Surrey', hub: 'brighton' },
  { name: 'Felbridge', slug: 'felbridge', county: 'Surrey', hub: 'brighton' },
  { name: 'Forest Row', slug: 'forest-row', county: 'East Sussex', hub: 'brighton' },
  { name: 'Ashurstwood', slug: 'ashurstwood', county: 'East Sussex', hub: 'brighton' },
  { name: 'Sharpthorne', slug: 'sharpthorne', county: 'East Sussex', hub: 'brighton' },
  { name: 'West Hoathly', slug: 'west-hoathly', county: 'West Sussex', hub: 'brighton' },
  { name: 'Ardingly', slug: 'ardingly', county: 'West Sussex', hub: 'brighton' },
  { name: 'Turners Hill', slug: 'turners-hill', county: 'West Sussex', hub: 'brighton' },
  { name: 'Worth', slug: 'worth', county: 'West Sussex', hub: 'brighton' },
  { name: 'Copthorne', slug: 'copthorne', county: 'West Sussex', hub: 'brighton' },
  { name: 'Burstow', slug: 'burstow', county: 'Surrey', hub: 'brighton' },
  { name: 'Smallfield', slug: 'smallfield', county: 'Surrey', hub: 'brighton' },
  { name: 'Hookwood', slug: 'hookwood', county: 'Surrey', hub: 'brighton' },
  { name: 'Charlwood', slug: 'charlwood', county: 'Surrey', hub: 'brighton' },
  { name: 'Ifield', slug: 'ifield', county: 'West Sussex', hub: 'brighton' },
  { name: 'Bewbush', slug: 'bewbush', county: 'West Sussex', hub: 'brighton' },
  { name: 'Broadfield', slug: 'broadfield', county: 'West Sussex', hub: 'brighton' },
  { name: 'Tilgate', slug: 'tilgate', county: 'West Sussex', hub: 'brighton' },
  { name: 'Furnace Green', slug: 'furnace-green', county: 'West Sussex', hub: 'brighton' },
  { name: 'Three Bridges', slug: 'three-bridges', county: 'West Sussex', hub: 'brighton' },
  { name: 'Pound Hill', slug: 'pound-hill', county: 'West Sussex', hub: 'brighton' },
  { name: 'Maidenbower', slug: 'maidenbower', county: 'West Sussex', hub: 'brighton' },
  { name: 'Balcombe', slug: 'balcombe', county: 'West Sussex', hub: 'brighton' },
  { name: 'Cuckfield', slug: 'cuckfield', county: 'West Sussex', hub: 'brighton' },
  { name: 'Whitemans Green', slug: 'whitemans-green', county: 'West Sussex', hub: 'brighton' },
  { name: 'Ansty', slug: 'ansty', county: 'West Sussex', hub: 'brighton' },
  { name: 'Wivelsfield', slug: 'wivelsfield', county: 'East Sussex', hub: 'brighton' },
  { name: 'Ditchling', slug: 'ditchling', county: 'East Sussex', hub: 'brighton' },
  { name: 'Westmeston', slug: 'westmeston', county: 'East Sussex', hub: 'brighton' },
  { name: 'Streat', slug: 'streat', county: 'East Sussex', hub: 'brighton' },
  { name: 'Plumpton', slug: 'plumpton', county: 'East Sussex', hub: 'brighton' },
  { name: 'East Chiltington', slug: 'east-chiltington', county: 'East Sussex', hub: 'brighton' },
  { name: 'Hamsey', slug: 'hamsey', county: 'East Sussex', hub: 'brighton' },
  { name: 'Barcombe', slug: 'barcombe', county: 'East Sussex', hub: 'brighton' },
  { name: 'Newick', slug: 'newick', county: 'East Sussex', hub: 'brighton' },
  { name: 'Fletching', slug: 'fletching', county: 'East Sussex', hub: 'brighton' },
  { name: 'Nutley', slug: 'nutley', county: 'East Sussex', hub: 'brighton' },
  { name: 'Dallington', slug: 'dallington', county: 'East Sussex', hub: 'brighton' },
  { name: 'Warbleton', slug: 'warbleton', county: 'East Sussex', hub: 'brighton' },
  { name: 'Rushlake Green', slug: 'rushlake-green', county: 'East Sussex', hub: 'brighton' },
  { name: 'Cowbeech', slug: 'cowbeech', county: 'East Sussex', hub: 'brighton' },
  { name: 'Hellingly', slug: 'hellingly', county: 'East Sussex', hub: 'brighton' },
  { name: 'Maynards Green', slug: 'maynards-green', county: 'East Sussex', hub: 'brighton' },
  { name: 'Old Heathfield', slug: 'old-heathfield', county: 'East Sussex', hub: 'brighton' },
  { name: 'Piltdown', slug: 'piltdown', county: 'East Sussex', hub: 'brighton' },
]

// ─── Portsmouth hub (SO + PO south) — south Hampshire + Isle of Wight
const PORTSMOUTH_AREAS: DeliveryArea[] = [
  { name: 'Southampton', slug: 'southampton', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Eastleigh', slug: 'eastleigh', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Winchester', slug: 'winchester', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Andover', slug: 'andover', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Totton', slug: 'totton', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Hedge End', slug: 'hedge-end', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Hythe', slug: 'hythe', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Lymington', slug: 'lymington', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'New Milton', slug: 'new-milton', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Ringwood', slug: 'ringwood', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Fordingbridge', slug: 'fordingbridge', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Portsmouth', slug: 'portsmouth', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Havant', slug: 'havant', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Waterlooville', slug: 'waterlooville', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Gosport', slug: 'gosport', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Fareham', slug: 'fareham', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Stubbington', slug: 'stubbington', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Lee-on-the-Solent', slug: 'lee-on-the-solent', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Cowes', slug: 'cowes', county: 'Isle of Wight', hub: 'portsmouth' },
  { name: 'Newport', slug: 'newport', county: 'Isle of Wight', hub: 'portsmouth' },
  { name: 'Ryde', slug: 'ryde', county: 'Isle of Wight', hub: 'portsmouth' },
  { name: 'Sandown', slug: 'sandown', county: 'Isle of Wight', hub: 'portsmouth' },
  { name: 'Shanklin', slug: 'shanklin', county: 'Isle of Wight', hub: 'portsmouth' },
  { name: 'Bishops Waltham', slug: 'bishops-waltham', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Wickham', slug: 'wickham', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Botley', slug: 'botley', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Swanwick', slug: 'swanwick', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Park Gate', slug: 'park-gate', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Warsash', slug: 'warsash', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Locks Heath', slug: 'locks-heath', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Titchfield', slug: 'titchfield', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Whiteley', slug: 'whiteley', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Chandlers Ford', slug: 'chandlers-ford', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Chilworth', slug: 'chilworth', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Bassett', slug: 'bassett', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Bitterne', slug: 'bitterne', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Woolston', slug: 'woolston', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Sholing', slug: 'sholing', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Thornhill', slug: 'thornhill', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Lordshill', slug: 'lordshill', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Millbrook', slug: 'millbrook', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Marchwood', slug: 'marchwood', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Dibden', slug: 'dibden', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Beaulieu', slug: 'beaulieu', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Hythe (Hants)', slug: 'hythe-hants', county: 'Hampshire', hub: 'portsmouth' },
  { name: 'Freshwater', slug: 'freshwater', county: 'Isle of Wight', hub: 'portsmouth' },
  { name: 'Yarmouth', slug: 'yarmouth', county: 'Isle of Wight', hub: 'portsmouth' },
  { name: 'Ventnor', slug: 'ventnor', county: 'Isle of Wight', hub: 'portsmouth' },
]

// ─── Merge all hub groups into the public DELIVERY_AREAS array
export const DELIVERY_AREAS: DeliveryArea[] = [
  ...SLOUGH_AREAS,
  ...HIGH_WYCOMBE_AREAS,
  ...READING_AREAS,
  ...GUILDFORD_AREAS,
  ...BASINGSTOKE_AREAS,
  ...OXFORD_AREAS,
  ...SWINDON_AREAS,
  ...LONDON_AREAS,
  ...LUTON_AREAS,
  ...SOUTHEND_AREAS,
  ...MAIDSTONE_AREAS,
  ...BRIGHTON_AREAS,
  ...PORTSMOUTH_AREAS,
]

/**
 * Human-readable label for each delivery hub — always a real city name.
 * We use the primary city in each hub so the labels read as cities
 * ("Slough", "Oxford", "City of London") rather than regions
 * ("Greater London", "South Hampshire"). The surrounding towns and
 * postcodes are surfaced in the searchable delivery-area list and the
 * body copy, so the region context isn't lost.
 */
export const DELIVERY_HUB_LABELS: Record<DeliveryHub, string> = {
  slough: 'Slough',
  'high-wycombe': 'High Wycombe',
  reading: 'Reading',
  guildford: 'Guildford',
  basingstoke: 'Basingstoke',
  oxford: 'Oxford',
  swindon: 'Swindon',
  london: 'City of London',
  luton: 'Luton',
  southend: 'Chelmsford',
  maidstone: 'Maidstone',
  brighton: 'Brighton',
  portsmouth: 'Southampton',
}

/** Slug for each hub's primary /locations/[slug] page. */
export const DELIVERY_HUB_SLUGS: Record<DeliveryHub, string> = {
  slough: 'slough',
  'high-wycombe': 'high-wycombe',
  reading: 'reading',
  guildford: 'guildford',
  basingstoke: 'basingstoke',
  oxford: 'oxford',
  swindon: 'swindon',
  london: 'hillingdon',
  luton: 'luton',
  southend: 'chelmsford',
  maidstone: 'maidstone',
  brighton: 'brighton',
  portsmouth: 'southampton',
}
