// lib/location-images.ts
// Cinematic golden-hour location hero images for the /locations/[town]
// pages. Replaces the old 4-yard-photo pool that cycled across 935 pages.
//
// Mapping strategy — three-tier fallback:
//   1. Explicit town override     — ~90 main towns get a hand-picked image
//   2. County pool                — each county has 4-6 curated images
//   3. General-purpose pool       — 50 generic English countryside + arch
//                                   imagery used as the catch-all for
//                                   towns with no override or county match
//
// Tier 2/3 selections use a stable slug-hash so:
//   - the same town always gets the same image (no flicker on refresh)
//   - neighbouring towns share an image family, so the network feels
//     cohesive rather than random
//
// Total: 60 place-specific + 50 general-purpose = 110 unique images
// across ~935 towns. Main towns get a perfect hand-picked match; every
// other town falls through to the same wide generic pool (50 ≈ enough
// variety for each image to serve ~18 pages on average).
//
// General-purpose images are generated by
// `scripts/generate-general-purpose-location-images.mjs` against
// `scripts/location-general-purpose-prompts.json`. They're generic on
// purpose — no place-specific landmark or named landscape — so they can
// be reused for any of the ~845 minor delivery towns without a visual
// "mismatch" (e.g. a random Bedfordshire town shouldn't show Canterbury
// Cathedral). The 60 place-specific images stay reserved for the towns
// that genuinely deserve them (in TOWN_OVERRIDES) or for curated county
// pools (in COUNTY_POOL).

import { readdirSync } from 'node:fs'
import { join } from 'node:path'

export type ImageCategory = 'town' | 'landmark' | 'scenery' | 'character'

/**
 * Slugs that have a rendered WebP on disk. Built once at module load.
 * Used as a safety net so partial rollouts of the general-purpose pool
 * don't 404 — if a town hash-picks a slug whose file hasn't landed yet,
 * we fall through to the hero fallback instead.
 */
const READY_SLUGS: ReadonlySet<string> = (() => {
  try {
    const dir = join(process.cwd(), 'public', 'locations')
    return new Set(
      readdirSync(dir)
        .filter((f) => f.endsWith('.webp'))
        .map((f) => f.slice(0, -'.webp'.length)),
    )
  } catch {
    // public/locations doesn't exist in some build setups — empty set
    // is fine, the LOCATION_IMAGES registry still functions.
    return new Set()
  }
})()


export interface LocationImage {
  readonly slug: string
  readonly path: string
  readonly baseAlt: string
  readonly category: ImageCategory
}

/**
 * Master image registry. Generated by `scripts/generate-location-images.mjs`
 * from `scripts/location-images-prompts.json` (50 cinematic golden-hour
 * WebP assets, 1920w q80, ~13MB total).
 */
export const LOCATION_IMAGES: readonly LocationImage[] = [
  { slug: 'guildford-high-street', path: '/locations/guildford-high-street.webp', baseAlt: 'Guildford High Street at golden hour with the Guildhall tower', category: 'town' },
  { slug: 'reading-town-centre', path: '/locations/reading-town-centre.webp', baseAlt: 'Reading town centre at golden hour', category: 'town' },
  { slug: 'basingstoke-town-centre', path: '/locations/basingstoke-town-centre.webp', baseAlt: 'Basingstoke town centre at golden hour with the Market Place', category: 'town' },
  { slug: 'oxford-cornmarket', path: '/locations/oxford-cornmarket.webp', baseAlt: 'Oxford Cornmarket Street at golden hour with college spires above', category: 'town' },
  { slug: 'maidstone-high-street', path: '/locations/maidstone-high-street.webp', baseAlt: 'Maidstone High Street at golden hour', category: 'town' },
  { slug: 'brighton-seafront', path: '/locations/brighton-seafront.webp', baseAlt: 'Brighton seafront and pier at golden hour', category: 'town' },
  { slug: 'southampton-city-centre', path: '/locations/southampton-city-centre.webp', baseAlt: 'Southampton city centre at golden hour with the Bargate', category: 'town' },
  { slug: 'portsmouth-dockyard', path: '/locations/portsmouth-dockyard.webp', baseAlt: 'Portsmouth Historic Dockyard at golden hour with HMS Warrior', category: 'town' },
  { slug: 'luton-town-centre', path: '/locations/luton-town-centre.webp', baseAlt: 'Luton town centre at golden hour', category: 'town' },
  { slug: 'chelmsford-high-street', path: '/locations/chelmsford-high-street.webp', baseAlt: 'Chelmsford High Street at golden hour', category: 'town' },
  { slug: 'slough-town-centre', path: '/locations/slough-town-centre.webp', baseAlt: 'Slough town centre at golden hour', category: 'town' },
  { slug: 'high-wycombe-town', path: '/locations/high-wycombe-town.webp', baseAlt: 'High Wycombe town centre at golden hour', category: 'town' },
  { slug: 'windsor-castle', path: '/locations/windsor-castle.webp', baseAlt: 'Windsor Castle at golden hour, Round Tower silhouetted', category: 'landmark' },
  { slug: 'tower-bridge-london', path: '/locations/tower-bridge-london.webp', baseAlt: 'Tower Bridge London at golden hour', category: 'landmark' },
  { slug: 'canterbury-cathedral', path: '/locations/canterbury-cathedral.webp', baseAlt: 'Canterbury Cathedral at golden hour', category: 'landmark' },
  { slug: 'hampton-court-palace', path: '/locations/hampton-court-palace.webp', baseAlt: 'Hampton Court Palace at golden hour', category: 'landmark' },
  { slug: 'blenheim-palace', path: '/locations/blenheim-palace.webp', baseAlt: 'Blenheim Palace at golden hour', category: 'landmark' },
  { slug: 'leeds-castle-kent', path: '/locations/leeds-castle-kent.webp', baseAlt: 'Leeds Castle in Kent at golden hour', category: 'landmark' },
  { slug: 'arundel-castle', path: '/locations/arundel-castle.webp', baseAlt: 'Arundel Castle at golden hour', category: 'landmark' },
  { slug: 'rochester-castle', path: '/locations/rochester-castle.webp', baseAlt: 'Rochester Castle at golden hour', category: 'landmark' },
  { slug: 'dover-white-cliffs', path: '/locations/dover-white-cliffs.webp', baseAlt: 'The White Cliffs of Dover at golden hour', category: 'landmark' },
  { slug: 'st-pauls-cathedral', path: '/locations/st-pauls-cathedral.webp', baseAlt: 'St Paul\'s Cathedral London at golden hour', category: 'landmark' },
  { slug: 'box-hill-surrey', path: '/locations/box-hill-surrey.webp', baseAlt: 'Box Hill Surrey Hills at golden hour', category: 'landmark' },
  { slug: 'seven-sisters-cliffs', path: '/locations/seven-sisters-cliffs.webp', baseAlt: 'Seven Sisters chalk cliffs at golden hour', category: 'landmark' },
  { slug: 'south-downs-hillside', path: '/locations/south-downs-hillside.webp', baseAlt: 'South Downs hillside with sheep at golden hour', category: 'scenery' },
  { slug: 'north-downs-chalk', path: '/locations/north-downs-chalk.webp', baseAlt: 'North Downs chalk escarpment at golden hour', category: 'scenery' },
  { slug: 'chilterns-beech-woods', path: '/locations/chilterns-beech-woods.webp', baseAlt: 'Chiltern Hills beech woodland at golden hour', category: 'scenery' },
  { slug: 'cotswolds-stone-village', path: '/locations/cotswolds-stone-village.webp', baseAlt: 'Cotswolds stone village at golden hour', category: 'scenery' },
  { slug: 'thames-goring', path: '/locations/thames-goring.webp', baseAlt: 'River Thames at Goring at golden hour', category: 'scenery' },
  { slug: 'kent-orchard-blossom', path: '/locations/kent-orchard-blossom.webp', baseAlt: 'Kent cherry orchard in blossom at golden hour', category: 'scenery' },
  { slug: 'surrey-heathland', path: '/locations/surrey-heathland.webp', baseAlt: 'Surrey heathland at golden hour', category: 'scenery' },
  { slug: 'test-valley-meadow', path: '/locations/test-valley-meadow.webp', baseAlt: 'Hampshire Test Valley water meadow at golden hour', category: 'scenery' },
  { slug: 'new-forest-ponies', path: '/locations/new-forest-ponies.webp', baseAlt: 'New Forest wild ponies at golden hour', category: 'scenery' },
  { slug: 'oxfordshire-village-green', path: '/locations/oxfordshire-village-green.webp', baseAlt: 'Oxfordshire village green at golden hour', category: 'scenery' },
  { slug: 'buckinghamshire-village', path: '/locations/buckinghamshire-village.webp', baseAlt: 'Buckinghamshire village at golden hour', category: 'scenery' },
  { slug: 'berkshire-downland', path: '/locations/berkshire-downland.webp', baseAlt: 'Berkshire downland at golden hour', category: 'scenery' },
  { slug: 'west-sussex-vineyard', path: '/locations/west-sussex-vineyard.webp', baseAlt: 'West Sussex vineyard at golden hour', category: 'scenery' },
  { slug: 'rye-cobbled-streets', path: '/locations/rye-cobbled-streets.webp', baseAlt: 'Rye cobbled streets at golden hour', category: 'scenery' },
  { slug: 'kent-hop-field', path: '/locations/kent-hop-field.webp', baseAlt: 'Kent hop field with oast houses at golden hour', category: 'scenery' },
  { slug: 'hampshire-chalk-stream', path: '/locations/hampshire-chalk-stream.webp', baseAlt: 'Hampshire chalk stream at golden hour', category: 'scenery' },
  { slug: 'cotswold-stone-cottage', path: '/locations/cotswold-stone-cottage.webp', baseAlt: 'Cotswold stone cottage at golden hour', category: 'character' },
  { slug: 'kentish-ragstone-wall', path: '/locations/kentish-ragstone-wall.webp', baseAlt: 'Kentish ragstone wall at golden hour', category: 'character' },
  { slug: 'tudor-timber-frame', path: '/locations/tudor-timber-frame.webp', baseAlt: 'Tudor timber-frame house at golden hour', category: 'character' },
  { slug: 'sussex-tile-hung-cottage', path: '/locations/sussex-tile-hung-cottage.webp', baseAlt: 'Sussex tile-hung cottage at golden hour', category: 'character' },
  { slug: 'georgian-terrace', path: '/locations/georgian-terrace.webp', baseAlt: 'Georgian terraced street at golden hour', category: 'character' },
  { slug: 'victorian-terrace-london', path: '/locations/victorian-terrace-london.webp', baseAlt: 'Victorian London terraced street at golden hour', category: 'character' },
  { slug: 'modern-extension-build', path: '/locations/modern-extension-build.webp', baseAlt: 'Modern extension under construction at golden hour', category: 'character' },
  { slug: 'oak-frame-barn', path: '/locations/oak-frame-barn.webp', baseAlt: 'Traditional oak-frame barn at golden hour', category: 'character' },
  { slug: 'brickworks-heritage', path: '/locations/brickworks-heritage.webp', baseAlt: 'Historic brickworks kiln at golden hour', category: 'character' },
  { slug: 'stone-bridge-river', path: '/locations/stone-bridge-river.webp', baseAlt: 'Ancient stone bridge over river at golden hour', category: 'character' },
  { slug: 'whitstable-harbour', path: '/locations/whitstable-harbour.webp', baseAlt: 'Whitstable harbour and beach huts at golden hour', category: 'town' },
  { slug: 'margate-seafront', path: '/locations/margate-seafront.webp', baseAlt: 'Margate seafront and harbour arm at golden hour', category: 'town' },
  { slug: 'ramsgate-harbour', path: '/locations/ramsgate-harbour.webp', baseAlt: 'Ramsgate royal harbour at golden hour', category: 'town' },
  { slug: 'broadstairs-victorian', path: '/locations/broadstairs-victorian.webp', baseAlt: 'Broadstairs Victorian seafront at golden hour', category: 'town' },
  { slug: 'deal-pier', path: '/locations/deal-pier.webp', baseAlt: 'Deal pier and seafront at golden hour', category: 'town' },
  { slug: 'newport-iow', path: '/locations/newport-iow.webp', baseAlt: 'Newport town centre Isle of Wight at golden hour', category: 'town' },
  { slug: 'ryde-seafront-iow', path: '/locations/ryde-seafront-iow.webp', baseAlt: 'Ryde esplanade Isle of Wight at golden hour', category: 'town' },
  { slug: 'sandown-bay-iow', path: '/locations/sandown-bay-iow.webp', baseAlt: 'Sandown Bay Isle of Wight at golden hour', category: 'town' },
  { slug: 'shanklin-old-village', path: '/locations/shanklin-old-village.webp', baseAlt: 'Shanklin Old Village Isle of Wight at golden hour', category: 'town' },
  { slug: 'ventnor-botanic', path: '/locations/ventnor-botanic.webp', baseAlt: 'Ventnor seaside and Undercliff Isle of Wight at golden hour', category: 'town' },
  // ─── Generic-purpose pool (50 place-agnostic images) ─────────────
  // Generated by scripts/generate-general-purpose-location-images.mjs.
  // No specific location references — these are reused for any of the
  // ~845 minor delivery towns that don't have a curated override or
  // county-pool match.
  { slug: 'english-country-lane-hedge', path: '/locations/english-country-lane-hedge.webp', baseAlt: 'An English country lane winding through rolling farmland at golden hour', category: 'scenery' },
  { slug: 'english-copse-autumn', path: '/locations/english-copse-autumn.webp', baseAlt: 'An English woodland copse in autumn backlit by low sun', category: 'scenery' },
  { slug: 'english-wheat-field-harvest', path: '/locations/english-wheat-field-harvest.webp', baseAlt: 'An English wheat field at harvest under a glowing sky', category: 'scenery' },
  { slug: 'english-rolling-fields-hedgerows', path: '/locations/english-rolling-fields-hedgerows.webp', baseAlt: 'Patchwork English farmland and hedgerows at golden hour', category: 'scenery' },
  { slug: 'english-footpath-stile-meadow', path: '/locations/english-footpath-stile-meadow.webp', baseAlt: 'An English footpath crossing a meadow at golden hour', category: 'scenery' },
  { slug: 'english-misty-meadow-willows', path: '/locations/english-misty-meadow-willows.webp', baseAlt: 'A misty English water meadow at dawn with willows', category: 'scenery' },
  { slug: 'english-bluebell-wood-edge', path: '/locations/english-bluebell-wood-edge.webp', baseAlt: 'The edge of an English bluebell wood in spring', category: 'scenery' },
  { slug: 'english-narrowboat-canal', path: '/locations/english-narrowboat-canal.webp', baseAlt: 'A traditional narrowboat on an English canal at golden hour', category: 'scenery' },
  { slug: 'english-river-meadow-bend', path: '/locations/english-river-meadow-bend.webp', baseAlt: 'An English river meandering through a water meadow', category: 'scenery' },
  { slug: 'english-chalkstream-alders', path: '/locations/english-chalkstream-alders.webp', baseAlt: 'A clear English chalk stream with alders at golden hour', category: 'scenery' },
  { slug: 'english-saltmarsh-sea-wall', path: '/locations/english-saltmarsh-sea-wall.webp', baseAlt: 'An English saltmarsh with a sea wall at golden hour', category: 'scenery' },
  { slug: 'english-pebble-beach-groynes', path: '/locations/english-pebble-beach-groynes.webp', baseAlt: 'An English pebble beach with wooden groynes at golden hour', category: 'scenery' },
  { slug: 'english-cliff-top-grass-path', path: '/locations/english-cliff-top-grass-path.webp', baseAlt: 'An English cliff top footpath overlooking the sea at golden hour', category: 'scenery' },
  { slug: 'english-cove-bay', path: '/locations/english-cove-bay.webp', baseAlt: 'A small English cove with chalk cliffs at golden hour', category: 'scenery' },
  { slug: 'english-autumn-tree-lane', path: '/locations/english-autumn-tree-lane.webp', baseAlt: 'An English autumn tree-lined country lane at golden hour', category: 'scenery' },
  { slug: 'english-ford-bridge-stream', path: '/locations/english-ford-bridge-stream.webp', baseAlt: 'An English ford crossing a stream under a stone bridge', category: 'scenery' },
  { slug: 'english-fenland-drain-channel', path: '/locations/english-fenland-drain-channel.webp', baseAlt: 'An English Fenland drainage channel under a vast sky at golden hour', category: 'scenery' },
  { slug: 'english-dandelion-meadow-pasture', path: '/locations/english-dandelion-meadow-pasture.webp', baseAlt: 'An English dandelion meadow in late spring at golden hour', category: 'scenery' },
  { slug: 'english-backlit-hedgerow-flare', path: '/locations/english-backlit-hedgerow-flare.webp', baseAlt: 'An English hedgerow backlit by the low sun with lens flare', category: 'scenery' },
  { slug: 'english-rustic-barn-pastoral', path: '/locations/english-rustic-barn-pastoral.webp', baseAlt: 'A rustic wooden English barn in pastoral countryside at golden hour', category: 'scenery' },
  { slug: 'english-sunset-fence-post', path: '/locations/english-sunset-fence-post.webp', baseAlt: 'A wooden fence post silhouetted against an English sunset', category: 'scenery' },
  { slug: 'english-village-pond-dusk', path: '/locations/english-village-pond-dusk.webp', baseAlt: 'An English village pond at dusk with a thatched cottage reflected', category: 'scenery' },
  { slug: 'english-frosty-dawn-tree', path: '/locations/english-frosty-dawn-tree.webp', baseAlt: 'A single English oak tree on a frosty dawn', category: 'scenery' },
  { slug: 'english-river-bend-poplars', path: '/locations/english-river-bend-poplars.webp', baseAlt: 'An English river bend lined with poplars at golden hour', category: 'scenery' },
  { slug: 'english-canal-lock-gates', path: '/locations/english-canal-lock-gates.webp', baseAlt: 'An English canal lock with closed gates at golden hour', category: 'scenery' },
  { slug: 'english-thatched-cottage-honey', path: '/locations/english-thatched-cottage-honey.webp', baseAlt: 'A traditional English thatched cottage at golden hour', category: 'character' },
  { slug: 'english-tile-hung-cottage-roses', path: '/locations/english-tile-hung-cottage-roses.webp', baseAlt: 'An English tile-hung cottage with roses at golden hour', category: 'character' },
  { slug: 'english-stone-cottage-arched-door', path: '/locations/english-stone-cottage-arched-door.webp', baseAlt: 'An English stone cottage with an arched door and wisteria', category: 'character' },
  { slug: 'english-flint-brick-cottage', path: '/locations/english-flint-brick-cottage.webp', baseAlt: 'An English brick-and-flint cottage at golden hour', category: 'character' },
  { slug: 'english-village-green-cottages', path: '/locations/english-village-green-cottages.webp', baseAlt: 'An English village green framed by cottages and a great oak', category: 'character' },
  { slug: 'english-parish-church-tower', path: '/locations/english-parish-church-tower.webp', baseAlt: 'An English parish church with a stone tower at golden hour', category: 'character' },
  { slug: 'english-countryside-pub', path: '/locations/english-countryside-pub.webp', baseAlt: 'A traditional English countryside pub at golden hour', category: 'character' },
  { slug: 'english-packhorse-stone-bridge', path: '/locations/english-packhorse-stone-bridge.webp', baseAlt: 'An ancient English packhorse stone bridge at golden hour', category: 'character' },
  { slug: 'english-almshouses-stone-row', path: '/locations/english-almshouses-stone-row.webp', baseAlt: 'A row of English stone almshouses at golden hour', category: 'character' },
  { slug: 'english-wayside-stone-cross', path: '/locations/english-wayside-stone-cross.webp', baseAlt: 'A medieval English wayside cross at golden hour', category: 'character' },
  { slug: 'english-tudor-arched-doorway', path: '/locations/english-tudor-arched-doorway.webp', baseAlt: 'An English Tudor arched stone doorway at golden hour', category: 'character' },
  { slug: 'english-war-memorial-village', path: '/locations/english-war-memorial-village.webp', baseAlt: 'An English village stone war memorial at golden hour', category: 'character' },
  { slug: 'english-brick-viaduct-arches', path: '/locations/english-brick-viaduct-arches.webp', baseAlt: 'An English red-brick Victorian railway viaduct at golden hour', category: 'character' },
  { slug: 'english-market-cross-pillars', path: '/locations/english-market-cross-pillars.webp', baseAlt: 'An English medieval stone market cross at golden hour', category: 'character' },
  { slug: 'english-victorian-schoolhouse', path: '/locations/english-victorian-schoolhouse.webp', baseAlt: 'An English Victorian village schoolhouse at golden hour', category: 'character' },
  { slug: 'english-climbing-roses-cottage', path: '/locations/english-climbing-roses-cottage.webp', baseAlt: 'An English whitewashed cottage with climbing pink roses at golden hour', category: 'character' },
  { slug: 'english-rose-garden-arch', path: '/locations/english-rose-garden-arch.webp', baseAlt: 'An English wrought-iron garden arch covered in climbing roses', category: 'character' },
  { slug: 'english-iron-lamppost-cobbles', path: '/locations/english-iron-lamppost-cobbles.webp', baseAlt: 'An ornate Victorian English lamppost at dusk on a cobbled lane', category: 'character' },
  { slug: 'english-painted-shopfront', path: '/locations/english-painted-shopfront.webp', baseAlt: 'A traditional English painted shopfront at golden hour', category: 'character' },
  { slug: 'english-flint-church-tower', path: '/locations/english-flint-church-tower.webp', baseAlt: 'An English rural flint-knapped church tower at golden hour', category: 'character' },
  { slug: 'english-stone-barn-farmyard', path: '/locations/english-stone-barn-farmyard.webp', baseAlt: 'An English stone-built barn in a farmyard at golden hour', category: 'character' },
  { slug: 'english-weatherboarded-barn-roof', path: '/locations/english-weatherboarded-barn-roof.webp', baseAlt: 'A traditional English weatherboarded barn at golden hour', category: 'character' },
  { slug: 'english-cricket-pitch-evening', path: '/locations/english-cricket-pitch-evening.webp', baseAlt: 'An English village cricket pitch at golden hour', category: 'character' },
  { slug: 'english-lychgate-churchyard', path: '/locations/english-lychgate-churchyard.webp', baseAlt: 'An English churchyard lychgate at golden hour', category: 'character' },
  { slug: 'english-vicarage-stone-wall', path: '/locations/english-vicarage-stone-wall.webp', baseAlt: 'An English vicarage garden wall with climbing hydrangea at golden hour', category: 'character' },
  // ─── Generic-purpose pool — batch 2 (10 extras) ──────────────────
  { slug: 'english-orchard-blossom-spring', path: '/locations/english-orchard-blossom-spring.webp', baseAlt: 'A traditional English orchard in full spring blossom at golden hour', category: 'scenery' },
  { slug: 'english-hill-fort-rampart', path: '/locations/english-hill-fort-rampart.webp', baseAlt: 'Ancient English hill fort ramparts at golden hour', category: 'scenery' },
  { slug: 'english-stone-circle-silhouette', path: '/locations/english-stone-circle-silhouette.webp', baseAlt: 'An ancient English stone circle silhouetted against the sunset', category: 'scenery' },
  { slug: 'english-cosy-pub-window', path: '/locations/english-cosy-pub-window.webp', baseAlt: 'A warm glowing English pub window at dusk', category: 'character' },
  { slug: 'english-dovecote-tower', path: '/locations/english-dovecote-tower.webp', baseAlt: 'An English stone dovecote tower at golden hour', category: 'character' },
  { slug: 'english-village-hall', path: '/locations/english-village-hall.webp', baseAlt: 'An English Victorian village hall at golden hour', category: 'character' },
  { slug: 'english-wooden-footbridge', path: '/locations/english-wooden-footbridge.webp', baseAlt: 'An English wooden footbridge over a stream at golden hour', category: 'character' },
  { slug: 'english-footpath-fingerpost', path: '/locations/english-footpath-fingerpost.webp', baseAlt: 'An English wooden footpath fingerpost at a crossroads', category: 'character' },
  { slug: 'english-stone-cross-stile', path: '/locations/english-stone-cross-stile.webp', baseAlt: 'An English medieval stone cross beside a stile at golden hour', category: 'character' },
  { slug: 'english-coastal-cliff-arch', path: '/locations/english-coastal-cliff-arch.webp', baseAlt: 'A natural English coastal rock arch at golden hour', category: 'scenery' },
  // ─── Generic-purpose pool — batch 3 (5 extras) ───────────────────
  { slug: 'english-allotment-rows', path: '/locations/english-allotment-rows.webp', baseAlt: 'An English allotment kitchen garden in summer sunlight', category: 'scenery' },
  { slug: 'english-fishing-boat-bow', path: '/locations/english-fishing-boat-bow.webp', baseAlt: 'A weathered English fishing boat bow at low tide', category: 'character' },
  { slug: 'english-window-box-geraniums', path: '/locations/english-window-box-geraniums.webp', baseAlt: 'An English cottage window box with red geraniums at golden hour', category: 'character' },
  { slug: 'english-allotment-greenhouse', path: '/locations/english-allotment-greenhouse.webp', baseAlt: 'An English allotment glasshouse at golden hour', category: 'character' },
  { slug: 'english-wisteria-cottage-front', path: '/locations/english-wisteria-cottage-front.webp', baseAlt: 'An English cottage front draped in wisteria at golden hour', category: 'character' },
] 

const IMAGE_BY_SLUG: ReadonlyMap<string, LocationImage> = new Map(
  LOCATION_IMAGES.map((img) => [img.slug, img]),
)

/**
 * Tier 1 — explicit town overrides. The ~70 most-visited delivery towns
 * get a hand-picked image that visually identifies the place. Everything
 * else falls through to the county pool.
 */
const TOWN_OVERRIDES: Readonly<Record<string, string>> = {
  // ─── Slough hub ─────────────────────────────────────────────
  slough: 'slough-town-centre',
  windsor: 'windsor-castle',
  maidenhead: 'thames-goring',
  bracknell: 'berkshire-downland',
  ascot: 'windsor-castle',
  eton: 'windsor-castle',

  // ─── High Wycombe hub ──────────────────────────────────────
  'high-wycombe': 'high-wycombe-town',
  aylesbury: 'chilterns-beech-woods',
  beaconsfield: 'chilterns-beech-woods',
  chesham: 'chilterns-beech-woods',
  amersham: 'chilterns-beech-woods',
  marlow: 'thames-goring',
  'princes-risborough': 'chilterns-beech-woods',
  'great-missenden': 'chilterns-beech-woods',

  // ─── Reading hub ───────────────────────────────────────────
  reading: 'reading-town-centre',
  'henley-on-thames': 'thames-goring',
  caversham: 'thames-goring',
  wokingham: 'berkshire-downland',
  newbury: 'berkshire-downland',
  hungerford: 'berkshire-downland',
  thatcham: 'berkshire-downland',

  // ─── Guildford hub ─────────────────────────────────────────
  guildford: 'guildford-high-street',
  woking: 'surrey-heathland',
  farnham: 'surrey-heathland',
  farnborough: 'surrey-heathland',
  aldershot: 'surrey-heathland',
  camberley: 'surrey-heathland',
  epsom: 'surrey-heathland',
  esher: 'surrey-heathland',
  leatherhead: 'box-hill-surrey',
  dorking: 'box-hill-surrey',
  reigate: 'box-hill-surrey',
  redhill: 'box-hill-surrey',
  godalming: 'surrey-heathland',
  haslemere: 'surrey-heathland',
  cranleigh: 'surrey-heathland',
  cobham: 'surrey-heathland',
  weybridge: 'thames-goring',
  'walton-on-thames': 'thames-goring',

  // ─── Basingstoke hub ───────────────────────────────────────
  basingstoke: 'basingstoke-town-centre',
  winchester: 'southampton-city-centre',
  alton: 'south-downs-hillside',
  odiham: 'test-valley-meadow',
  hook: 'test-valley-meadow',
  whitchurch: 'test-valley-meadow',
  tadley: 'south-downs-hillside',

  // ─── Oxford hub ────────────────────────────────────────────
  oxford: 'oxford-cornmarket',
  banbury: 'oxfordshire-village-green',
  bicester: 'oxfordshire-village-green',
  witney: 'oxfordshire-village-green',
  abingdon: 'thames-goring',
  didcot: 'thames-goring',
  wallingford: 'thames-goring',
  thame: 'oxfordshire-village-green',
  wantage: 'berkshire-downland',

  // ─── Swindon hub ───────────────────────────────────────────
  swindon: 'oxford-cornmarket',
  marlborough: 'oxfordshire-village-green',

  // ─── Luton hub ─────────────────────────────────────────────
  luton: 'luton-town-centre',
  'st-albans': 'georgian-terrace',
  watford: 'victorian-terrace-london',
  'hemel-hempstead': 'chilterns-beech-woods',
  bedford: 'georgian-terrace',
  'milton-keynes': 'modern-extension-build',
  dunstable: 'georgian-terrace',
  harpenden: 'georgian-terrace',
  hertford: 'georgian-terrace',
  stevenage: 'georgian-terrace',
  hitchin: 'georgian-terrace',
  berkhamsted: 'chilterns-beech-woods',
  'leighton-buzzard': 'oak-frame-barn',

  // ─── Southend (Chelmsford) hub ─────────────────────────────
  chelmsford: 'chelmsford-high-street',
  'southend-on-sea': 'victorian-terrace-london',
  brentwood: 'victorian-terrace-london',
  colchester: 'rochester-castle',
  harlow: 'victorian-terrace-london',
  romford: 'victorian-terrace-london',
  ilford: 'victorian-terrace-london',

  // ─── Maidstone hub ─────────────────────────────────────────
  maidstone: 'maidstone-high-street',
  canterbury: 'canterbury-cathedral',
  rochester: 'rochester-castle',
  chatham: 'rochester-castle',
  dover: 'dover-white-cliffs',
  folkestone: 'dover-white-cliffs',
  ashford: 'kent-orchard-blossom',
  sevenoaks: 'kentish-ragstone-wall',
  'tunbridge-wells': 'kentish-ragstone-wall',
  tonbridge: 'kentish-ragstone-wall',
  dartford: 'rochester-castle',
  gravesend: 'rochester-castle',
  // Kent coastal towns
  whitstable: 'whitstable-harbour',
  margate: 'margate-seafront',
  ramsgate: 'ramsgate-harbour',
  broadstairs: 'broadstairs-victorian',
  deal: 'deal-pier',
  sittingbourne: 'kent-orchard-blossom',
  faversham: 'whitstable-harbour',
  farningham: 'kentish-ragstone-wall',
  eynsford: 'kentish-ragstone-wall',
  'westgate-on-sea': 'margate-seafront',
  'birchington-on-sea': 'margate-seafront',
  'herne-bay': 'whitstable-harbour',
  sandwich: 'deal-pier',
  tenterden: 'kent-hop-field',
  cranbrook: 'kent-hop-field',

  // ─── Brighton hub ──────────────────────────────────────────
  brighton: 'brighton-seafront',
  hove: 'brighton-seafront',
  crawley: 'south-downs-hillside',
  horsham: 'south-downs-hillside',
  'east-grinstead': 'surrey-heathland',
  chichester: 'arundel-castle',
  worthing: 'seven-sisters-cliffs',
  eastbourne: 'seven-sisters-cliffs',
  hastings: 'rye-cobbled-streets',
  lewes: 'seven-sisters-cliffs',
  littlehampton: 'seven-sisters-cliffs',
  'bognor-regis': 'arundel-castle',

  // ─── Southampton (Portsmouth) hub ──────────────────────────
  southampton: 'southampton-city-centre',
  portsmouth: 'portsmouth-dockyard',
  eastleigh: 'southampton-city-centre',
  gosport: 'portsmouth-dockyard',
  fareham: 'portsmouth-dockyard',
  havant: 'portsmouth-dockyard',
  // Isle of Wight
  cowes: 'newport-iow',
  newport: 'newport-iow',
  ryde: 'ryde-seafront-iow',
  sandown: 'sandown-bay-iow',
  shanklin: 'shanklin-old-village',
  ventnor: 'ventnor-botanic',
  freshwater: 'ventnor-botanic',
  yarmouth: 'ventnor-botanic',

  // ─── City of London hub ───────────────────────────────────
  // Spread across boroughs — landmark London shots win where relevant
  london: 'st-pauls-cathedral',
  westminster: 'st-pauls-cathedral',
  richmond: 'hampton-court-palace',
  kingston: 'hampton-court-palace',
  twickenham: 'hampton-court-palace',
  bromley: 'victorian-terrace-london',
  croydon: 'victorian-terrace-london',
}

/**
 * Tier 2 — county pool. 4-6 images per county, curated for locality.
 * Falls back through here when no explicit town override exists.
 */
const COUNTY_POOL: Readonly<Record<string, readonly string[]>> = {
  Surrey: [
    'box-hill-surrey',
    'surrey-heathland',
    'guildford-high-street',
    'sussex-tile-hung-cottage',
    'tudor-timber-frame',
  ],
  Kent: [
    'canterbury-cathedral',
    'rochester-castle',
    'leeds-castle-kent',
    'kent-orchard-blossom',
    'kent-hop-field',
    'kentish-ragstone-wall',
  ],
  'East Sussex': [
    'seven-sisters-cliffs',
    'brighton-seafront',
    'rye-cobbled-streets',
    'south-downs-hillside',
    'georgian-terrace',
  ],
  'West Sussex': [
    'arundel-castle',
    'west-sussex-vineyard',
    'south-downs-hillside',
    'sussex-tile-hung-cottage',
    'seven-sisters-cliffs',
  ],
  Hampshire: [
    'southampton-city-centre',
    'portsmouth-dockyard',
    'test-valley-meadow',
    'south-downs-hillside',
    'hampshire-chalk-stream',
    'new-forest-ponies',
  ],
  Berkshire: [
    'windsor-castle',
    'thames-goring',
    'berkshire-downland',
    'chilterns-beech-woods',
    'tudor-timber-frame',
  ],
  Buckinghamshire: [
    'chilterns-beech-woods',
    'blenheim-palace',
    'buckinghamshire-village',
    'tudor-timber-frame',
    'stone-bridge-river',
  ],
  Oxfordshire: [
    'oxford-cornmarket',
    'blenheim-palace',
    'oxfordshire-village-green',
    'cotswolds-stone-village',
    'cotswold-stone-cottage',
  ],
  Wiltshire: [
    'cotswolds-stone-village',
    'oxfordshire-village-green',
    'stone-bridge-river',
    'tudor-timber-frame',
    'brickworks-heritage',
  ],
  Hertfordshire: [
    'victorian-terrace-london',
    'georgian-terrace',
    'chilterns-beech-woods',
    'tudor-timber-frame',
    'modern-extension-build',
  ],
  Bedfordshire: [
    'georgian-terrace',
    'oak-frame-barn',
    'modern-extension-build',
    'victorian-terrace-london',
    'brickworks-heritage',
  ],
  Essex: [
    'chelmsford-high-street',
    'victorian-terrace-london',
    'kent-orchard-blossom',
    'rochester-castle',
    'brickworks-heritage',
  ],
  'Greater London': [
    'tower-bridge-london',
    'st-pauls-cathedral',
    'victorian-terrace-london',
    'georgian-terrace',
    'hampton-court-palace',
  ],
  'Isle of Wight': [
    'portsmouth-dockyard',
    'southampton-city-centre',
    'seven-sisters-cliffs',
    'hampshire-chalk-stream',
    'new-forest-ponies',
  ],
  Slough: [
    'windsor-castle',
    'thames-goring',
    'chilterns-beech-woods',
    'tudor-timber-frame',
    'stone-bridge-river',
  ],
}

/**
 * Tier 3 — general-purpose pool. 50 place-agnostic images used as the
 * catch-all fallback for any town without an explicit override AND
 * without a curated county-pool match. The pool is intentionally
 * generic (a random Bedfordshire town shouldn't show Canterbury
 * Cathedral), so the SAME wide pool serves every region that doesn't
 * have curated coverage.
 *
 * Order is stable so the djb2 hash on town slugs picks deterministically.
 */
const GENERAL_POOL: readonly string[] = [
  // Scenery (25) — generic English countryside/landscape
  'english-country-lane-hedge',
  'english-copse-autumn',
  'english-wheat-field-harvest',
  'english-rolling-fields-hedgerows',
  'english-footpath-stile-meadow',
  'english-misty-meadow-willows',
  'english-bluebell-wood-edge',
  'english-narrowboat-canal',
  'english-river-meadow-bend',
  'english-chalkstream-alders',
  'english-saltmarsh-sea-wall',
  'english-pebble-beach-groynes',
  'english-cliff-top-grass-path',
  'english-cove-bay',
  'english-autumn-tree-lane',
  'english-ford-bridge-stream',
  'english-fenland-drain-channel',
  'english-dandelion-meadow-pasture',
  'english-backlit-hedgerow-flare',
  'english-rustic-barn-pastoral',
  'english-sunset-fence-post',
  'english-village-pond-dusk',
  'english-frosty-dawn-tree',
  'english-river-bend-poplars',
  'english-canal-lock-gates',
  // Character (25) — generic English architecture/structures
  'english-thatched-cottage-honey',
  'english-tile-hung-cottage-roses',
  'english-stone-cottage-arched-door',
  'english-flint-brick-cottage',
  'english-village-green-cottages',
  'english-parish-church-tower',
  'english-countryside-pub',
  'english-packhorse-stone-bridge',
  'english-almshouses-stone-row',
  'english-wayside-stone-cross',
  'english-tudor-arched-doorway',
  'english-war-memorial-village',
  'english-brick-viaduct-arches',
  'english-market-cross-pillars',
  'english-victorian-schoolhouse',
  'english-climbing-roses-cottage',
  'english-rose-garden-arch',
  'english-iron-lamppost-cobbles',
  'english-painted-shopfront',
  'english-flint-church-tower',
  'english-stone-barn-farmyard',
  'english-weatherboarded-barn-roof',
  'english-cricket-pitch-evening',
  'english-lychgate-churchyard',
  'english-vicarage-stone-wall',
  // batch 2 — 10 extras
  'english-orchard-blossom-spring',
  'english-hill-fort-rampart',
  'english-stone-circle-silhouette',
  'english-cosy-pub-window',
  'english-dovecote-tower',
  'english-village-hall',
  'english-wooden-footbridge',
  'english-footpath-fingerpost',
  'english-stone-cross-stile',
  'english-coastal-cliff-arch',
  // batch 3 — 5 extras
  'english-allotment-rows',
  'english-fishing-boat-bow',
  'english-window-box-geraniums',
  'english-allotment-greenhouse',
  'english-wisteria-cottage-front',
] 

/** Final fallback if every tier is empty. Should never trigger in practice. */
const FALLBACK_PATH = '/hero-1-4kgen.webp'

/**
 * Deterministic djb2 hash → stable index. Same slug always returns the
 * same image; flipping entries in a pool only reshuffles the mapping
 * for newly-affected slugs.
 */
function pickStable<T>(seed: string, pool: readonly T[]): T {
  if (pool.length === 0) {
    throw new Error('location-images: empty pool')
  }
  let h = 5381
  for (let i = 0; i < seed.length; i++) {
    h = ((h << 5) + h + seed.charCodeAt(i)) | 0
  }
  return pool[Math.abs(h) % pool.length]
}

/**
 * Resolve the hero image for a /locations/[town] page.
 *
 * @returns the WebP path + locality-aware alt text. Alt always references
 * the actual town so Google Images can rank each page for its area.
 */
export function getLocationImage(
  townSlug: string,
  // `_hub` retained for API compat with call sites; the new tier-3
  // general-purpose pool is region-agnostic, so the hub is no longer
  // used to choose an image.
  _hub: string,
  county: string,
  town: string,
): { path: string; alt: string } {
  const fallback = {
    path: FALLBACK_PATH,
    alt: `Building materials and aggregates being delivered to ${town}, ${county}`,
  }

  let imageSlug: string | undefined

  // Tier 1 — explicit town override
  imageSlug = TOWN_OVERRIDES[townSlug]

  // Tier 2 — county pool, picked by slug hash
  if (!imageSlug) {
    const countyImages = COUNTY_POOL[county]
    if (countyImages && countyImages.length > 0) {
      imageSlug = pickStable(townSlug, countyImages)
    }
  }

  // Tier 3 — general-purpose pool, picked by slug hash across the 50
  // generic images so every tier-3 town deterministically gets the
  // same image on every render.
  if (!imageSlug) {
    imageSlug = pickStable(townSlug, GENERAL_POOL)
  }

  if (!imageSlug) return fallback

  const img = IMAGE_BY_SLUG.get(imageSlug)
  if (!img) return fallback

  // Safety net: if the picked slug's WebP hasn't been generated yet
  // (partial rollout of the general-purpose pool), fall through to the
  // hero fallback instead of returning a path that would 404.
  if (!READY_SLUGS.has(imageSlug)) return fallback

  return {
    path: img.path,
    alt: `${img.baseAlt}, near ${town}, ${county}`,
  }
} 