import { z } from 'zod'

/**
 * Minimal runtime schema for the invoice preview payload used by the
 * PDF and send-email API routes. This rejects obviously malformed or
 * malicious payloads while remaining permissive enough for legitimate
 * preview data generated by the invoice form.
 */
export const previewInvoiceSchema = z.object({
  invoice: z.object({
    type: z.enum(['invoice', 'quotation']),
    document_number: z.string().min(1),
    issue_date: z.string().min(1),
    issue_time: z.string().nullable().optional(),
    due_date: z.string().nullable().optional(),
    expiry_date: z.string().nullable().optional(),
    order_number: z.string().nullable().optional(),
    account_number: z.string().nullable().optional(),
    operator_name: z.string().optional(),
    your_reference: z.string().nullable().optional(),
    notes: z.string().nullable().optional(),
    show_payment_terms: z.boolean().nullable().optional(),
    // New in 102 — toggles the centred, low-opacity logo watermark on the
    // invoice PDF + on-screen document.
    show_watermark: z.boolean().nullable().optional(),
    // New in 103 — three status-driven rubber-stamp toggles (PAID /
    // PARTIALLY PAID / OVERDUE) and the tracking fields that feed the
    // operator-name + date lines on the stamp itself.
    show_paid_watermark: z.boolean().nullable().optional(),
    show_partially_paid_watermark: z.boolean().nullable().optional(),
    show_overdue_watermark: z.boolean().nullable().optional(),
    paid_by: z.string().nullable().optional(),
    paid_at: z.string().nullable().optional(),
    overdue_at: z.string().nullable().optional(),
    // New in 104 — master switch + Auto/Manual mode for the status-stamp
    // feature. `status_stamps_mode` is constrained to 'auto' | 'manual' at
    // the DB level; we accept either string here for forward-compat.
    status_stamps_enabled: z.boolean().nullable().optional(),
    status_stamps_mode: z.enum(['auto', 'manual']).nullable().optional(),
    status: z.string().nullable().optional(),
    updated_at: z.string().nullable().optional(),
    subtotal: z.number(),
    vat_total: z.number(),
    total: z.number(),
    amount_paid: z.number().optional(),
    balance_due: z.number().optional(),
    delivery_method: z.enum(['delivery', 'collection']).nullable().optional(),
    delivery_address_line_1: z.string().nullable().optional(),
    delivery_address_line_2: z.string().nullable().optional(),
    delivery_town: z.string().nullable().optional(),
    delivery_county: z.string().nullable().optional(),
    delivery_postcode: z.string().nullable().optional(),
    // Order-level discount — added with the manual-discount feature so the
    // preview PDF can show the "Discount −£X" row. Optional because not
    // every preview carries one.
    discount_amount: z.number().nullable().optional(),
    discount_percent: z.number().nullable().optional(),
    clients: z.union([
      z.object({
        first_name: z.string().nullable(),
        last_name: z.string().nullable(),
        company_name: z.string().nullable(),
        address_line_1: z.string().nullable().optional(),
        address_line_2: z.string().nullable().optional(),
        town: z.string().nullable().optional(),
        county: z.string().nullable().optional(),
        postcode: z.string().nullable().optional(),
        email: z.string().nullable().optional(),
        phone: z.string().nullable().optional(),
      }),
      z.array(
        z.object({
          first_name: z.string().nullable(),
          last_name: z.string().nullable(),
          company_name: z.string().nullable(),
          address_line_1: z.string().nullable().optional(),
          address_line_2: z.string().nullable().optional(),
          town: z.string().nullable().optional(),
          county: z.string().nullable().optional(),
          postcode: z.string().nullable().optional(),
          email: z.string().nullable().optional(),
          phone: z.string().nullable().optional(),
        })
      ),
    ]),
    invoice_items: z
      .array(
        z.object({
          product_name: z.string().min(1),
          product_code: z.string().nullable().optional(),
          unit: z.string().nullable().optional(),
          quantity: z.number(),
          price: z.number(),
          vat_rate: z.number(),
          vat_amount: z.number(),
          line_total: z.number(),
          // Per-line discount values — optional so older preview callers
          // that don't include them still pass validation.
          discount_amount: z.number().nullable().optional(),
          discount_percent: z.number().nullable().optional(),
        })
      )
      .optional(),
  }),
})

export type PreviewInvoicePayload = z.infer<typeof previewInvoiceSchema>
