"""
scripts/remove-logo-background.py

Drop the background off  C:\\Users\\sarpa\\Desktop\\Logo.png  using rembg's
isnet-general-use model + alpha matting, post-process the alpha to crisp it
up (sub-pixel unsharp on the alpha channel then a single hard threshold),
trim to bbox, and overwrite public/Logo.png with the clean transparent
canonical composite.

Run once per source refresh; the variant fan-out is generated by the
companion script  scripts/generate-logo-variants.mjs .

Memory: this combination (isnet-general-use + alpha_matting with
foreground_threshold=240, background_threshold=10, erode_size=5, then
alpha unsharp + hard threshold at 128) gives a near-binary alpha that
sharpens the letterform edges back to their original crispness — the soft
fringe you get from raw alpha_matting softens the mark at small icon sizes.
"""

from pathlib import Path
import numpy as np
from PIL import Image, ImageFilter
from rembg import new_session, remove

SRC = Path(r"C:\Users\sarpa\Desktop\Logo.png")
DST = Path(r"C:\Users\sarpa\PycharmProjects\SWBM\public\Logo.png")


def crisp_alpha(rgba: Image.Image) -> Image.Image:
    """Tighten alpha-matting's soft edges back to binary so the mark stays
    crisp at 16×16 favicon size. Pipeline:
      1. extract alpha channel
      2. unsharp-mask it (boosts the steep mid-tone transition)
      3. hard threshold at 128 → binary
      4. paste the crisp alpha back onto the RGB channels (untouched)
    """
    r, g, b, a = rgba.split()
    # Mild unsharp: 2-px radius, 200% amount. Pushes the alpha transition
    # closer to the original hard edge.
    crisp = a.filter(ImageFilter.UnsharpMask(radius=2, percent=200, threshold=0))
    crisp = crisp.point(lambda v: 255 if v >= 128 else 0)
    return Image.merge("RGBA", (r, g, b, crisp))


def main() -> None:
    print(f"loading  {SRC}")
    src = Image.open(SRC).convert("RGBA")
    print(f"  source size  {src.size}")

    print("loading rembg session  isnet-general-use …")
    session = new_session("isnet-general-use")

    print("removing background …")
    raw = remove(
        np.array(src),
        session=session,
        alpha_matting=True,
        alpha_matting_foreground_threshold=240,
        alpha_matting_background_threshold=10,
        alpha_matting_erode_size=5,
    )
    rgba = Image.fromarray(raw, mode="RGBA")

    print("crisp-ing alpha …")
    rgba = crisp_alpha(rgba)

    print("trimming transparent padding …")
    bbox = rgba.getbbox()
    if bbox is None:
        raise RuntimeError("rembg returned an empty alpha — check the source")
    rgba = rgba.crop(bbox)
    print(f"  trimmed size  {rgba.size}")

    DST.parent.mkdir(parents=True, exist_ok=True)
    rgba.save(DST, format="PNG", optimize=True)
    print(f"wrote  {DST}  ({DST.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()