-- =============================================================================
-- Star Hawk Builders Merchant — 064_temporary_clients_and_products.sql
-- =============================================================================
-- Adds the "temporary record" concept to clients and products.
--
-- A *temporary* record is one created quickly from inside an invoice or quote
-- (e.g. via the inline "+ New" affordance in ClientPicker / ProductSearch).
-- It captures the bare minimum needed to issue the document and is then
-- expected to be fleshed out by staff afterwards. Important properties:
--
--   * The dedicated create pages (/clients/new, /admin/products/new) NEVER create
--     temporary rows — only the invoice/quote pickers do. This keeps the main
--     list trustworthy.
--   * Temporary rows are NEVER auto-deleted. Invoices reference them by FK,
--     so deleting would orphan the document. They sit in a dedicated
--     "Temporary clients / products" dashboard section until a staff/admin
--     fills them in and gets auto-promoted to a permanent row.
--   * Auto-promote happens inside updateClientRecord / updateProductRecord:
--     once the row meets the minimum completeness criteria, the next save
--     flips is_temporary=false and stamps promoted_at.
--
-- Products need a NOT NULL `code`. To keep the schema clean we don't relax
-- the constraint — quick-add generates a `TEMP-XXXXXX` placeholder, flagged
-- via temp_placeholder_code=true so the dashboard can show "real code missing".
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. clients
-- -----------------------------------------------------------------------------
ALTER TABLE public.clients
  ADD COLUMN IF NOT EXISTS is_temporary boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS promoted_at timestamptz;

COMMENT ON COLUMN public.clients.is_temporary IS
  'Quick-add rows created from inside an invoice/quote. Listed in the dashboard "Temporary clients" section until promoted. Auto-promoted to false when updateClientRecord detects the row is now complete.';
COMMENT ON COLUMN public.clients.promoted_at IS
  'When a temporary client was promoted to permanent (is_temporary flipped to false). Null for never-temporary rows.';

-- Partial index — the dashboard filter is "is_temporary = true" so we only
-- need to index the rare temp subset.
CREATE INDEX IF NOT EXISTS idx_clients_is_temporary
  ON public.clients (is_temporary)
  WHERE is_temporary = true;

-- -----------------------------------------------------------------------------
-- 2. products
-- -----------------------------------------------------------------------------
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS is_temporary boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS promoted_at timestamptz,
  ADD COLUMN IF NOT EXISTS temp_placeholder_code boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.products.is_temporary IS
  'Quick-add rows created from inside an invoice/quote. Listed in the dashboard "Temporary products" section until promoted. Auto-promoted to false when updateProductRecord detects the row is now complete.';
COMMENT ON COLUMN public.products.promoted_at IS
  'When a temporary product was promoted to permanent (is_temporary flipped to false). Null for never-temporary rows.';
COMMENT ON COLUMN public.products.temp_placeholder_code IS
  'When true, products.code is a TEMP-XXXXXX placeholder auto-generated by the quick-add path. Surfaces "real code still missing" in the dashboard section.';

CREATE INDEX IF NOT EXISTS idx_products_is_temporary
  ON public.products (is_temporary)
  WHERE is_temporary = true;

-- -----------------------------------------------------------------------------
-- 3. RLS — no changes needed
-- -----------------------------------------------------------------------------
-- The quick-add path runs from the same authenticated staff/admin sessions as
-- the existing create flows, so the existing RLS policies (per-row ownership
-- for staff, admin-all for admins) already cover temp rows correctly. We do
-- not want any policy that lets a temp row bypass the ownership check.
-- =============================================================================
