-- =============================================================================
-- 159_promote_temporary_products.sql
-- =============================================================================
-- Promotes the 10 walk-in (TEMPORARY) products visible in the dashboard
-- screenshot into permanent catalogue entries. The operator captures these
-- on the fly as walk-in invoice line items via the QuickProductAdder
-- helper; this migration gives them real codes, categories, descriptions,
-- search tags and SEO so the public catalogue and search pick them up.
--
-- 7 new permanent products are inserted:
--
--   AGG-010  Post Mix Concrete
--   BLO-005  Marshall Block Paving Pallet
--   FIX-017  Weep Vents
--   BLO-006  Air Brick Buff
--   STL-077  Floor Beam 4.2m
--   AGG-011  Pavemix
--   AGG-012  Luxury Porcelain Slabs
--
-- 3 of the 10 screenshot rows are NOT migrated because:
--
--   * Ibstock Red Multi          -> already a permanent product (BRI-033)
--   * Cavitywall Insulation 150mm -> already a permanent product (CAV-008)
--   * Fuel surcharge             -> service charge, not a physical product
--
-- The 3 original temporary rows stay in the dashboard so the operator can
-- decide what to do with them (edit and fill in details, or hard-delete
-- via the trash icon in the Temporary products list).
--
-- Idempotency: every INSERT is `ON CONFLICT (code) DO UPDATE` so re-running
-- the migration updates the existing rows in place without duplicating.
-- =============================================================================

BEGIN;
-- ────────────────────────────────────────────────────────────────────────────
-- INSERT 7 new permanent products
-- ────────────────────────────────────────────────────────────────────────────

INSERT INTO public.products (
  code,
  name,
  description,
  unit,
  category,
  default_price,
  image_url,
  is_active,
  seo_title,
  seo_description,
  short_description,
  key_features,
  search_tags,
  brand,
  mpn,
  applications,
  length_mm,
  width_mm,
  height_mm,
  thickness_mm,
  coverage_m2_per_unit,
  coverage_linear_m_per_unit,
  unit_weight_kg,
  pack_size,
  wastage_pct,
  calculator_type,
  materials,
  variant_options,
  family_slug,
  source_url
) VALUES
  ('AGG-010',
   'Post Mix Concrete',
   'Post Mix Concrete is a fast-setting ready-to-use concrete mix for fence posts, gate posts, deck posts and small structural fixings. Just add water — no mixing required. Sets in minutes for quick fence and sign installations. Supplied in 20kg bags.',
   'BAG',
   'Aggregates & Cement',
   0,
   '/products/post-mix-concrete.webp',
   true,
   'Post Mix Concrete 20kg | Star Hawk Builders Merchant',
   'Order Post Mix Concrete online. Fast-setting ready-mix concrete for fence posts, gate posts and deck posts. 20kg bag, same-day delivery from Star Hawk.',
   'Fast-setting ready-mix concrete for fence and gate posts.',
   '[]'::jsonb,
   ARRAY['post mix', 'postmix', 'postcrete', 'fence post concrete', 'post mix concrete', 'ready mix', 'ready-mix', 'fast set', 'fast-set', 'fence post mix', 'concrete post'],
   NULL,
   NULL,
   to_jsonb(ARRAY['Fence post installation', 'Gate post setting', 'Deck post bases', 'Sign post fixing', 'Rotary line posts']),
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   5,
   NULL,
   to_jsonb(ARRAY['Concrete', 'Cement']),
   NULL,
   NULL,
   NULL),
  ('BLO-005',
   'Marshall Block Paving Pallet',
   'Marshall Block Paving Pallet is a standard-sized block paving pallet covering approximately 10-12m² depending on block size. Standard 50mm thickness for domestic driveways, patios and paths. Available in Charcoal, Brindle, Burnt Ochre and Natural. Contact the trade counter for current colours and a delivered price.',
   'EA',
   'Blocks',
   0,
   '/products/marshall-block-paving.webp',
   true,
   'Marshall Block Paving Pallet | Star Hawk Builders Merchant',
   'Order Marshall Block Paving Pallet online. Standard 50mm block paving, ~10-12m² per pallet for driveways and patios. Trade price and site delivery from Star Hawk.',
   'Standard block paving pallet (~10-12m²) for domestic driveways and patios.',
   '[]'::jsonb,
   ARRAY['block paving', 'marshall', 'paving slab', 'driveway block', 'patio block', 'pallet paving', 'block pave', 'paving stone', 'paving', 'concrete block paving'],
   NULL,
   NULL,
   to_jsonb(ARRAY['Domestic driveways', 'Garden patios', 'Paths and walkways', 'Parking areas']),
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   5,
   NULL,
   to_jsonb(ARRAY['Concrete']),
   NULL,
   NULL,
   NULL),
  ('FIX-017',
   'Weep Vents',
   'Weep Vents are small plastic or stainless-steel vent inserts fitted in the perpend joints of external brickwork to drain moisture from cavity walls. Standard colour-matched to brick mortar. Pack of 50.',
   'EA',
   'Fixings',
   0,
   '/products/weep-vents.webp',
   true,
   'Weep Vents | Star Hawk Builders Merchant',
   'Order Weep Vents online. Cavity wall drainage inserts for external brickwork. Trade pack of 50, same-day delivery from Star Hawk.',
   'Cavity wall weep vents for drainage through brickwork.',
   '[]'::jsonb,
   ARRAY['weep vent', 'weep hole', 'cavity vent', 'wall vent', 'brick vent', 'drainage vent', 'cavity drainage', 'weep', 'vent', 'wall weep'],
   NULL,
   NULL,
   to_jsonb(ARRAY['External brickwork drainage', 'Cavity wall venting', 'Above DPC']),
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   5,
   NULL,
   to_jsonb(ARRAY['Plastic']),
   NULL,
   NULL,
   NULL),
  ('BLO-006',
   'Air Brick Buff',
   'Air Brick Buff is a buff-coloured air brick for through-wall ventilation in suspended floors, sub-floor voids and cavity walls. Standard 215x140mm face size to suit a 9x6 inch opening. Manufactured in a buff/sandstone colour to match lighter brickwork.',
   'EA',
   'Blocks',
   0,
   '/products/air-brick-buff.webp',
   true,
   'Air Brick Buff | Star Hawk Builders Merchant',
   'Order Air Brick Buff online. Buff-coloured through-wall air brick for sub-floor and cavity ventilation. Standard 215x140mm, trade price from Star Hawk.',
   'Buff-coloured air brick for sub-floor and cavity ventilation.',
   '[]'::jsonb,
   ARRAY['air brick', 'airbrick', 'buff air brick', 'ventilation brick', 'sub floor vent', 'cavity vent', 'through wall vent', 'air vent', 'floor vent'],
   NULL,
   NULL,
   to_jsonb(ARRAY['Suspended floor ventilation', 'Sub-floor void venting', 'Cavity wall ventilation', 'Garage sub-floor vents']),
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   5,
   NULL,
   to_jsonb(ARRAY['Clay']),
   NULL,
   NULL,
   NULL),
  ('STL-077',
   'Floor Beam 4.2m',
   'Floor Beam 4.2m is a pre-stressed concrete floor beam for ground and upper floors. Standard 4.2 metre length, 150mm deep, designed to work with concrete block infill. Trade price per beam — quantity discount available for full floor kits.',
   'EA',
   'Steel & Lintels',
   0,
   '/products/floor-beam-concrete.webp',
   true,
   'Floor Beam 4.2m | Star Hawk Builders Merchant',
   'Order Floor Beam 4.2m online. Pre-stressed concrete floor beam for ground and upper floors. Trade price and site delivery from Star Hawk.',
   'Pre-stressed concrete floor beam, 4.2 metre length.',
   '[]'::jsonb,
   ARRAY['floor beam', 'concrete floor beam', 'pre-stressed beam', 'prestressed beam', '4.2m beam', '4.2 metre beam', 'ground floor beam', 'upper floor beam', 'floor joist'],
   NULL,
   NULL,
   to_jsonb(ARRAY['Ground floor construction', 'Upper floor construction', 'Extensions', 'Garage floors']),
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   5,
   NULL,
   to_jsonb(ARRAY['Concrete', 'Pre-stressed concrete']),
   NULL,
   NULL,
   NULL),
  ('AGG-011',
   'Pavemix',
   'Pavemix is a pre-blended sand and cement paving mix for laying slabs, paviors and block paving bedding. Just add water, mix and lay. Supplied in 20kg bags. Trade pack pricing for full paving projects.',
   'BAG',
   'Aggregates & Cement',
   0,
   '/products/pavemix.webp',
   true,
   'Pavemix | Star Hawk Builders Merchant',
   'Order Pavemix online. Pre-blended sand and cement paving mix for laying slabs, paviors and block paving. 20kg bag, same-day delivery from Star Hawk.',
   'Pre-blended sand and cement paving mix for slabs and paviors.',
   '[]'::jsonb,
   ARRAY['pavemix', 'paving mix', 'slab mix', 'patio mix', 'sand cement mix', 'paving sand', 'mortar mix', 'paving bed', 'paving base'],
   NULL,
   NULL,
   to_jsonb(ARRAY['Laying paving slabs', 'Setting paviors', 'Block paving bedding', 'Patio construction']),
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   5,
   NULL,
   to_jsonb(ARRAY['Sand', 'Cement']),
   NULL,
   NULL,
   NULL),
  ('AGG-012',
   'Luxury Porcelain Slabs',
   'Luxury Porcelain Slabs are large-format 20mm porcelain paving for premium patios, terraces and balconies. 600x600mm standard, available in Marble, Stone and Wood-effect finishes. Sold per square metre — order in full packs. Trade price on application.',
   'M2',
   'Aggregates & Cement',
   0,
   '/products/luxury-porcelain-slabs.webp',
   true,
   'Luxury Porcelain Slabs | Star Hawk Builders Merchant',
   'Order Luxury Porcelain Slabs online. 20mm porcelain paving in Marble, Stone and Wood-effect finishes for premium patios and terraces. Trade price per m² from Star Hawk.',
   'Large-format 20mm porcelain paving slabs for premium patios.',
   '[]'::jsonb,
   ARRAY['porcelain slab', 'porcelain paving', 'luxury paving', '20mm porcelain', 'large format slab', 'patio slab', 'porcelain tile', 'outdoor porcelain', 'premium paving'],
   NULL,
   NULL,
   to_jsonb(ARRAY['Premium patios', 'Terraces', 'Balconies', 'Roof terraces']),
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   5,
   NULL,
   to_jsonb(ARRAY['Porcelain']),
   NULL,
   NULL,
   NULL)

ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  unit = EXCLUDED.unit,
  category = EXCLUDED.category,
  image_url = EXCLUDED.image_url,
  is_active = true,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  short_description = EXCLUDED.short_description,
  search_tags = EXCLUDED.search_tags,
  applications = EXCLUDED.applications,
  materials = EXCLUDED.materials;

COMMIT;



